import { createActionProposal, listRecentProposalsByAction, type ActionProposalView, type CreateProposalInput } from "../../../actions/proposals";
import type { AsanaResource } from "./types";
import { ASANA_PROVIDER } from "./types";
import { asanaPlainText } from "./plainText";
export const ASANA_SELECTION_ACTION_ID="asana.lastSelection";
export const ASANA_ENTITY_CONTEXT_ACTION_ID="asana.entityContext";
const LIST_TTL=30*60*1000,ENTITY_TTL=2*60*60*1000;
export interface AsanaContextItem{id:string;type:string;title:string;completed:boolean|null;project:string|null;section:string|null;due:string|null;permalink:string|null}
export interface AsanaStore{create?:(u:string,i:CreateProposalInput)=>Promise<{id:string}>;listRecent?:(u:string,a:string)=>Promise<ActionProposalView[]>}
export function toAsanaContextItem(raw:AsanaResource):AsanaContextItem{const memberships=Array.isArray(raw.memberships)?raw.memberships as Record<string,unknown>[]:[];const first=memberships[0];const named=(v:unknown)=>v&&typeof v==="object"&&typeof(v as {name?:unknown}).name==="string"?asanaPlainText((v as {name:string}).name)||null:null;return{id:raw.gid,type:typeof raw.resource_type==="string"?raw.resource_type:"task",title:asanaPlainText(raw.name)||"Untitled",completed:typeof raw.completed==="boolean"?raw.completed:null,project:named(first?.project)??(Array.isArray(raw.projects)?named(raw.projects[0]):null),section:named(first?.section),due:typeof raw.due_at==="string"?raw.due_at:typeof raw.due_on==="string"?raw.due_on:null,permalink:typeof raw.permalink_url==="string"&&raw.permalink_url.startsWith("https://app.asana.com/")?raw.permalink_url:null};}
function parseItem(v:unknown):AsanaContextItem|null{if(!v||typeof v!=="object")return null;const r=v as Record<string,unknown>;if(typeof r.id!=="string"||typeof r.title!=="string")return null;return{id:r.id,type:typeof r.type==="string"?r.type:"task",title:r.title,completed:typeof r.completed==="boolean"?r.completed:null,project:typeof r.project==="string"?r.project:null,section:typeof r.section==="string"?r.section:null,due:typeof r.due==="string"?r.due:null,permalink:typeof r.permalink==="string"?r.permalink:null};}
async function recent(userId:string,actionId:string,store:AsanaStore){return(store.listRecent??listRecentProposalsByAction)(userId,actionId);}
export async function recordAsanaSelection(userId:string,resources:AsanaResource[],store:AsanaStore={}):Promise<{id:string}>{const items=resources.slice(0,20).map(toAsanaContextItem);return(store.create??createActionProposal)(userId,{provider:ASANA_PROVIDER,actionId:ASANA_SELECTION_ACTION_ID,riskLevel:"read",confirmationRequired:false,input:{kind:"asana_selection",items},previewText:`Showed ${items.length} Asana results.`,ttlMs:LIST_TTL});}
export async function loadAsanaSelection(userId:string,store:AsanaStore={}):Promise<AsanaContextItem[]>{for(const row of await recent(userId,ASANA_SELECTION_ACTION_ID,store)){if(Date.parse(row.expiresAt)<=Date.now()||row.input?.kind!=="asana_selection"||!Array.isArray(row.input.items))continue;const items=row.input.items.map(parseItem);if(items.every(Boolean))return items as AsanaContextItem[];}return[];}
export async function recordAsanaEntity(userId:string,item:AsanaContextItem,actedKind:string|null,store:AsanaStore={}):Promise<{id:string}>{return(store.create??createActionProposal)(userId,{provider:ASANA_PROVIDER,actionId:ASANA_ENTITY_CONTEXT_ACTION_ID,riskLevel:"read",confirmationRequired:false,input:{kind:"asana_entity_context",item,actedKind,at:new Date().toISOString()},previewText:"Asana conversation context.",ttlMs:ENTITY_TTL});}
export async function loadAsanaEntity(userId:string,store:AsanaStore={}):Promise<AsanaContextItem|null>{for(const row of await recent(userId,ASANA_ENTITY_CONTEXT_ACTION_ID,store)){if(Date.parse(row.expiresAt)<=Date.now()||row.input?.kind!=="asana_entity_context")continue;const item=parseItem(row.input.item);if(item?.type==="deleted")return null;if(item)return item;}return null;}
export function parseAsanaOrdinal(text:string|undefined):number|null{const t=(text??"").trim().toLowerCase();const words:{[k:string]:number}={first:1,second:2,third:3,fourth:4,fifth:5,sixth:6,seventh:7,eighth:8,ninth:9,tenth:10};for(const[k,n]of Object.entries(words))if(new RegExp(`\\b${k}\\b`).test(t))return n;const ordinal=/\b(\d{1,2})(?:st|nd|rd|th)\b/.exec(t),bare=/^(\d{1,2})$/.exec(t),match=ordinal??bare;return match?Math.min(Number(match[1]),20):null;}
const REFERENCE_ONLY=/^(?:(?:it|its|that|this)(?:\s+(?:task|one))?|the\s+(?:task|one)(?:\s+you\s+just\s+(?:showed|created|updated|assigned|moved|commented\s+on|completed|reopened))?)$/i;
export function isAsanaReferencePhrase(value:string|null|undefined):boolean{return REFERENCE_ONLY.test((value??"").trim().replace(/[.!?]+$/g,""));}
export async function resolveAsanaReference(userId:string,text:string|undefined,targetPosition:number|null|undefined,targetPhrase:string|null|undefined,store:AsanaStore={}):Promise<{item:AsanaContextItem|null;ambiguous:boolean}>{const list=await loadAsanaSelection(userId,store);const position=targetPosition??parseAsanaOrdinal(text);if(position)return{item:list[position-1]??null,ambiguous:false};const phrase=(targetPhrase??"").trim().toLowerCase();if(phrase&&!isAsanaReferencePhrase(phrase)){const matches=list.filter(i=>i.title.toLowerCase().includes(phrase));return{item:matches.length===1?matches[0]!:null,ambiguous:matches.length>1};}return{item:await loadAsanaEntity(userId,store),ambiguous:false};}
