import { getUserTimezone } from "../../../reminders/reminders";
import { logger } from "../../../utils/logger";
import { AsanaError } from "./client";
import { isAsanaReferencePhrase, recordAsanaEntity, recordAsanaSelection, resolveAsanaReference, toAsanaContextItem } from "./asanaContext";
import { asanaUnsupportedLimitation, extractAsanaIntent, explicitProvider, shouldConsiderAsana, type AsanaIntent, type AsanaTextGenerator } from "./asanaIntentExtract";
import { getAsanaResource, getCurrentAsanaUser, listAsanaChildren, listAsanaResources, listAsanaTasks, normalizeAsanaTask } from "./operations";
import { asanaPlainText } from "./plainText";
import { resolveAsanaTaskTitle } from "./asanaTaskResolver";
import { searchAsanaTasksInWorkspace } from "./operations";
import type { AsanaResource } from "./types";

export interface AsanaReadDeps { extract?:typeof extractAsanaIntent; generate?:AsanaTextGenerator; getTimezone?:(u:string)=>Promise<string|undefined>; listTasks?:typeof listAsanaTasks; listResources?:typeof listAsanaResources; searchWorkspace?:typeof searchAsanaTasksInWorkspace; listChildren?:typeof listAsanaChildren; getResource?:typeof getAsanaResource; getCurrentUser?:typeof getCurrentAsanaUser; recordSelection?:typeof recordAsanaSelection; recordEntity?:typeof recordAsanaEntity; resolveReference?:typeof resolveAsanaReference; now?:Date; arbitrated?:boolean }
const errorReply=(error:unknown)=>error instanceof AsanaError&&error.reason==="not_connected"?"Your Asana isn’t connected, so I can’t see that work.":error instanceof AsanaError&&error.reason==="plan_restricted"?"Asana says that feature isn’t included in your current plan.":error instanceof AsanaError&&(error.reason==="forbidden"||error.reason==="reconnect_required")?"I don’t have permission to read that in Asana. You may need to reconnect or ask an Asana admin.":"I couldn’t reach Asana just now — mind trying again in a bit?";
const named=(value:unknown)=>value&&typeof value==="object"&&typeof(value as {name?:unknown}).name==="string"?asanaPlainText((value as {name:string}).name)||null:null;
const localParts=(date:Date,timeZone:string)=>Object.fromEntries(new Intl.DateTimeFormat("en-GB",{timeZone,year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(date).filter(p=>p.type!=="literal").map(p=>[p.type,p.value]));
const dateKey=(date:Date,timeZone:string)=>{const p=localParts(date,timeZone);return`${p.year}-${p.month}-${p.day}`;};
const addLocalDays=(date:string,days:number)=>{const [y,m,d]=date.split("-").map(Number);return new Date(Date.UTC(y!,m!-1,d!+days)).toISOString().slice(0,10);};
const calendarLabel=(date:string,today:string)=>date===today?"Today":date===addLocalDays(today,1)?"Tomorrow":new Intl.DateTimeFormat("en-GB",{timeZone:"UTC",weekday:"short",day:"numeric",month:"short"}).format(new Date(`${date}T12:00:00Z`));
const timeLabel=(date:Date,timeZone:string)=>new Intl.DateTimeFormat("en-GB",{timeZone,hour:"numeric",minute:"2-digit",hour12:true}).format(date).replace(":00","").replace(/\s/g,"").toLowerCase();
export function formatAsanaDate(value:string,timeZone:string,now=new Date()):string|null{if(/^\d{4}-\d{2}-\d{2}$/.test(value))return calendarLabel(value,dateKey(now,timeZone));const parsed=new Date(value);if(Number.isNaN(parsed.getTime()))return null;const localDate=dateKey(parsed,timeZone);return`${calendarLabel(localDate,dateKey(now,timeZone))} at ${timeLabel(parsed,timeZone)}`;}
export function formatAsanaItem(item:AsanaResource,index:number|undefined,timeZone:string,now=new Date()):string{const prefix=index?`${index}. `:"";const title=asanaPlainText(typeof item.name==="string"?item.name:typeof item.text==="string"?item.text:"")||"Untitled";const bits:string[]=[];if(item.completed===true)bits.push("complete");if(item.archived===true)bits.push("archived");const assignee=named(item.assignee);if(assignee)bits.push(assignee);const start=typeof item.start_at==="string"?formatAsanaDate(item.start_at,timeZone,now):typeof item.start_on==="string"?formatAsanaDate(item.start_on,timeZone,now):null;if(start)bits.push(`starts ${start}`);const due=typeof item.due_at==="string"?formatAsanaDate(item.due_at,timeZone,now):typeof item.due_on==="string"?formatAsanaDate(item.due_on,timeZone,now):null;if(due)bits.push(`due ${due}`);if(typeof item.duration_minutes==="number")bits.push(`${item.duration_minutes} min`);if(typeof item.entered_on==="string"){const entered=formatAsanaDate(item.entered_on,timeZone,now);if(entered)bits.push(entered);}const memberships=Array.isArray(item.memberships)?item.memberships as Record<string,unknown>[]:[];const project=named(memberships[0]?.project),section=named(memberships[0]?.section);if(project)bits.push(section?`${project} · ${section}`:project);let result=`${prefix}${title}${bits.length?` — ${bits.join(" · ")}`:""}`;if(index===undefined){const description=asanaPlainText(item.notes)||asanaPlainText(item.html_notes);if(description)result+=`\nDescription: ${description}`;const status=item.current_status&&typeof item.current_status==="object"?item.current_status as Record<string,unknown>:null,statusText=status?(asanaPlainText(status.title)||asanaPlainText(status.text)):"";if(statusText)result+=`\nStatus: ${statusText}`;const metric=item.metric&&typeof item.metric==="object"?item.metric as Record<string,unknown>:null;if(metric&&typeof metric.current_number_value==="number"&&typeof metric.target_number_value==="number")result+=`\nProgress: ${metric.current_number_value} of ${metric.target_number_value}`;}return result;}

const values=(value:unknown)=>Array.isArray(value)?value as Record<string,unknown>[]:[];
const names=(value:unknown)=>values(value).map(named).filter((name):name is string=>Boolean(name));
const fieldValue=(field:Record<string,unknown>)=>asanaPlainText(field.display_value) || named(field.enum_value) || (typeof field.text_value==="string"?asanaPlainText(field.text_value):"") || (typeof field.number_value==="number"?String(field.number_value):"");
export function formatAsanaTaskDetails(task:AsanaResource,subtasks:AsanaResource[]|null,dependencies:AsanaResource[]|null,timeZone:string,now=new Date()):string{
  const lines=[`Task: ${asanaPlainText(task.name)||"Untitled"}`,`Status: ${task.completed===true?"Complete":"Open"}`];
  lines.push(`Assignee: ${named(task.assignee)??"Unassigned"}`);
  const start=typeof task.start_at==="string"?formatAsanaDate(task.start_at,timeZone,now):typeof task.start_on==="string"?formatAsanaDate(task.start_on,timeZone,now):null;
  const due=typeof task.due_at==="string"?formatAsanaDate(task.due_at,timeZone,now):typeof task.due_on==="string"?formatAsanaDate(task.due_on,timeZone,now):null;
  if(start)lines.push(`Starts: ${start}`);if(due)lines.push(`Due: ${due}`);
  const memberships=values(task.memberships);const project=named(memberships[0]?.project)??names(task.projects)[0];const section=named(memberships[0]?.section);if(project)lines.push(`Project: ${project}`);if(section)lines.push(`Section: ${section}`);
  const notes=asanaPlainText(task.notes);if(notes)lines.push(`Description: ${notes}`);
  const custom=values(task.custom_fields).map(field=>{const name=named(field),value=fieldValue(field);return name&&value?`${name}: ${value}`:null;}).filter((value):value is string=>Boolean(value));if(custom.length)lines.push(`Custom fields: ${custom.join("; ")}`);
  const followerNames=names(task.followers);if(followerNames.length)lines.push(`Followers: ${followerNames.join(", ")}`);
  const dependencyNames=dependencies===null?null:dependencies.map(item=>asanaPlainText(item.name)).filter(Boolean);if(dependencyNames===null)lines.push("Dependencies: unavailable");else if(dependencyNames.length)lines.push(`Dependencies: ${dependencyNames.join(", ")}`);
  if(subtasks===null)lines.push("Subtasks: unavailable");else if(subtasks.length)lines.push(`Subtasks: ${subtasks.slice(0,10).map(item=>`${item.completed===true?"Complete":"Open"} — ${asanaPlainText(item.name)}`).join("; ")}`);
  return lines.join("\n");
}
function resourceKind(intent:AsanaIntent):"workspaces"|"users"|"teams"|"projects"|"portfolios"|"goals"|"tags"|"custom_fields"|null{if(intent.entity==="workspace")return"workspaces";if(intent.entity==="user")return"users";if(intent.entity==="team")return"teams";if(intent.entity==="project")return"projects";if(intent.entity==="portfolio")return"portfolios";if(intent.entity==="goal")return"goals";if(intent.entity==="tag")return"tags";if(intent.entity==="custom_field")return"custom_fields";return null;}
const nounFor=(entity:AsanaIntent["entity"]|string|null|undefined)=>({project:"project",task:"task",subtask:"subtask",section:"section",portfolio:"portfolio",goal:"goal",team:"team",comment:"comment",story:"comment",attachment:"attachment",dependency:"dependency",time_entry:"time entry",time_tracking_entry:"time entry",tag:"tag",user:"person",workspace:"workspace",membership:"membership",custom_field:"custom field",follower:"follower"}[entity??"task"]??"result");
const plural=(noun:string,count:number)=>count===1?noun:noun==="time entry"?"time entries":noun.endsWith("y")?`${noun.slice(0,-1)}ies`:`${noun}s`;
function contextResourceKind(type:string):Parameters<typeof getAsanaResource>[1]{const kinds:Record<string,Parameters<typeof getAsanaResource>[1]>={task:"tasks",project:"projects",goal:"goals",portfolio:"portfolios",team:"teams",user:"users",workspace:"workspaces",tag:"tags",custom_field:"custom_fields",attachment:"attachments",story:"stories",time_tracking_entry:"time_tracking_entries"};return kinds[type]??"tasks";}
async function resolveReadWorkspace(userId:string,intent:AsanaIntent,deps:AsanaReadDeps):Promise<{workspace:AsanaResource|null;reply?:string}>{const workspaces=await(deps.listResources??listAsanaResources)(userId,"workspaces",{count:100});if(!workspaces.length)return{workspace:null,reply:"I couldn’t find an accessible Asana workspace."};if(intent.workspaceName){const needle=intent.workspaceName.trim().toLowerCase();const matches=workspaces.filter(w=>typeof w.name==="string"&&w.name.trim().toLowerCase()===needle);if(matches.length===1)return{workspace:matches[0]!};if(matches.length>1)return{workspace:null,reply:"I found multiple Asana workspaces with that name. Which exact workspace do you mean?"};return{workspace:null,reply:`I couldn’t find an Asana workspace called “${intent.workspaceName}”.`};}if(workspaces.length===1)return{workspace:workspaces[0]!};const names=workspaces.slice(0,8).map(w=>typeof w.name==="string"?w.name:"Unnamed workspace").join(", ");return{workspace:null,reply:`Which Asana workspace should I use? I can access: ${names}.`};}
const exactNamed=(resources:AsanaResource[],value:string)=>resources.filter(r=>typeof r.name==="string"&&r.name.trim().toLowerCase()===value.trim().toLowerCase());
function responseHeader(noun:string,count:number,projectName:string|null):string{if(projectName)return count===1?`Here’s 1 ${noun} in ${asanaPlainText(projectName)}:`:`Here are ${count} ${plural(noun,count)} in ${asanaPlainText(projectName)}:`;return count===1?`Here’s your Asana ${noun}:`:`Here are your ${count} Asana ${plural(noun,count)}:`;}
async function detailChildren(userId:string,taskId:string,child:"subtasks"|"dependencies",deps:AsanaReadDeps):Promise<AsanaResource[]|null>{try{return await(deps.listChildren??listAsanaChildren)(userId,"tasks",taskId,child,10);}catch{return null;}}

export async function handleAsanaRead(userId:string,text:string|undefined,deps:AsanaReadDeps={}):Promise<{handled:boolean;reply?:string}>{
  if(!deps.arbitrated&&!shouldConsiderAsana(text))return{handled:false};
  try{
    const now=deps.now??new Date();const timezone=await(deps.getTimezone??getUserTimezone)(userId)??"UTC";const intent=await(deps.extract??extractAsanaIntent)({text:text??"",now:now.toISOString(),timezone,providerContext:deps.arbitrated?"asana":undefined,generate:deps.generate});
    if(!intent||intent.provider!=="asana"||intent.mode!=="read"||explicitProvider(text)==="todoist")return{handled:false};
    const limitation=asanaUnsupportedLimitation(intent.entity);if(limitation)return{handled:true,reply:limitation};
    const count=intent.count??10;let resources:AsanaResource[]=[];let responseEntity:AsanaIntent["entity"]|string|null=intent.entity??"task";let parentProject:string|null=null;let detailTask:AsanaResource|null=null;
    const readsTaskChildren=["subtask","dependency","comment","attachment","time_entry"].includes(intent.entity??"");const pronoun=!readsTaskChildren&&((!intent.targetPhrase&&/\b(?:it|its|that|this|one)\b/i.test(text??""))||isAsanaReferencePhrase(intent.targetPhrase));
    if(intent.targetPosition||pronoun){const resolved=await(deps.resolveReference??resolveAsanaReference)(userId,text,intent.targetPosition,intent.targetPhrase);if(!resolved.item)return{handled:true,reply:"I’m not sure which Asana entity you mean — could you name it or show the list again?"};responseEntity=resolved.item.type;const kind=contextResourceKind(resolved.item.type);resources=[await(deps.getResource??getAsanaResource)(userId,kind,resolved.item.id)];if(kind==="tasks"){detailTask=normalizeAsanaTask(resources[0]);if(!detailTask)throw new AsanaError("malformed_response");resources=[detailTask];}}
    else if((intent.entity??"task")==="task"&&intent.targetPhrase&&!isAsanaReferencePhrase(intent.targetPhrase)){const resolved=await resolveAsanaTaskTitle(userId,intent.targetPhrase,{listResources:deps.listResources,listTasks:deps.listTasks,searchWorkspace:deps.searchWorkspace});if(resolved.kind==="ambiguous")return{handled:true,reply:`I found multiple Asana tasks matching “${asanaPlainText(intent.targetPhrase)}”. Which exact task do you mean?`};if(resolved.kind==="not_found")return{handled:true,reply:`I couldn’t find an accessible Asana task matching “${asanaPlainText(intent.targetPhrase)}”.`};detailTask=normalizeAsanaTask(await(deps.getResource??getAsanaResource)(userId,"tasks",resolved.task.gid));if(!detailTask)throw new AsanaError("malformed_response");resources=[detailTask];responseEntity="task";}
    else if(intent.entity==="project"&&intent.portfolioName){const ws=await resolveReadWorkspace(userId,intent,deps);if(!ws.workspace)return{handled:true,reply:ws.reply};const portfolios=await(deps.listResources??listAsanaResources)(userId,"portfolios",{workspace:ws.workspace.gid,count:500}),matches=exactNamed(portfolios,intent.portfolioName);if(matches.length!==1)return{handled:true,reply:matches.length>1?"I found multiple Asana portfolios with that name. Which exact one?":`I couldn’t find an Asana portfolio called “${intent.portfolioName}”.`};parentProject=intent.portfolioName;resources=await(deps.listChildren??listAsanaChildren)(userId,"portfolios",matches[0]!.gid,"items",count);}
    else if(resourceKind(intent)&&intent.targetPhrase&&!isAsanaReferencePhrase(intent.targetPhrase)){const kind=resourceKind(intent)!;let candidates:AsanaResource[];if(kind==="workspaces")candidates=await(deps.listResources??listAsanaResources)(userId,kind,{count:100});else{const ws=await resolveReadWorkspace(userId,intent,deps);if(!ws.workspace)return{handled:true,reply:ws.reply};candidates=await(deps.listResources??listAsanaResources)(userId,kind,{workspace:ws.workspace.gid,archived:kind==="projects"?intent.archived??false:undefined,count:500});}const needle=intent.targetPhrase.trim().toLowerCase(),exactMatches=candidates.filter(resource=>typeof resource.name==="string"&&resource.name.trim().toLowerCase()===needle),partial=exactMatches.length?exactMatches:candidates.filter(resource=>typeof resource.name==="string"&&resource.name.toLowerCase().includes(needle));if(partial.length!==1)return{handled:true,reply:partial.length>1?`I found multiple Asana ${plural(nounFor(intent.entity),2)} matching “${asanaPlainText(intent.targetPhrase)}”. Which exact one do you mean?`:`I couldn’t find an accessible Asana ${nounFor(intent.entity)} matching “${asanaPlainText(intent.targetPhrase)}”.`};resources=[await(deps.getResource??getAsanaResource)(userId,kind,partial[0]!.gid)];}
    else{
      const childMap:{[key:string]:"subtasks"|"dependencies"|"dependents"|"stories"|"attachments"|"time_tracking_entries"}={subtask:"subtasks",dependency:/\b(?:dependents|blocking|blocked by it)\b/i.test(text??"")?"dependents":"dependencies",comment:"stories",attachment:"attachments",time_entry:"time_tracking_entries"};const child=intent.entity?childMap[intent.entity]:undefined;
      if(child){const ref=await(deps.resolveReference??resolveAsanaReference)(userId,text,intent.targetPosition,intent.targetPhrase);if(!ref.item)return{handled:true,reply:"Show me or name the Asana task first so I know which one you mean."};resources=await(deps.listChildren??listAsanaChildren)(userId,"tasks",ref.item.id,child,count);}
      else if((intent.entity??"task")==="task"&&intent.projectName){const ws=await resolveReadWorkspace(userId,intent,deps);if(!ws.workspace)return{handled:true,reply:ws.reply};const projects=await(deps.listResources??listAsanaResources)(userId,"projects",{workspace:ws.workspace.gid,count:500});const matches=exactNamed(projects,intent.projectName);if(matches.length!==1)return{handled:true,reply:matches.length>1?"I found multiple Asana projects with that name. Which exact one?":`I couldn’t find an Asana project called “${intent.projectName}”.`};parentProject=typeof matches[0]!.name==="string"?matches[0]!.name:intent.projectName;resources=await(deps.listTasks??listAsanaTasks)(userId,{project:matches[0]!.gid,count});}
      else{const kind=resourceKind(intent);if(kind==="users"&&intent.person&&/^(?:me|myself|self|current_user)$/i.test(intent.person)){resources=[await(deps.getCurrentUser??getCurrentAsanaUser)(userId)];}else{const requiresWorkspace=kind!==null&&["users","teams","projects","portfolios","goals","tags","custom_fields"].includes(kind);if(requiresWorkspace||kind===null){const ws=await resolveReadWorkspace(userId,intent,deps);if(!ws.workspace)return{handled:true,reply:ws.reply};resources=kind?await(deps.listResources??listAsanaResources)(userId,kind,{workspace:ws.workspace.gid,archived:kind==="projects"?intent.archived??false:undefined,count}):await(deps.listTasks??listAsanaTasks)(userId,{assignee:"me",workspace:ws.workspace.gid,count:Math.max(count,50)});}else resources=await(deps.listResources??listAsanaResources)(userId,kind,{count});}}
      if((responseEntity??"task")==="task")resources=resources.map(normalizeAsanaTask).filter((resource):resource is AsanaResource=>resource!==null);if(intent.query)resources=resources.filter(r=>typeof r.name==="string"&&r.name.toLowerCase().includes(intent.query!.toLowerCase()));if(intent.completed!==null&&intent.completed!==undefined)resources=resources.filter(r=>r.completed===intent.completed);resources=resources.slice(0,count);
    }
    if(!resources.length)return{handled:true,reply:parentProject?`I couldn’t find any tasks in ${asanaPlainText(parentProject)}.`:`I couldn’t find any matching Asana ${plural(nounFor(responseEntity),2)}.`};
    if(detailTask){const[subtasks,dependencies]=await Promise.all([detailChildren(userId,detailTask.gid,"subtasks",deps),detailChildren(userId,detailTask.gid,"dependencies",deps)]);await(deps.recordEntity??recordAsanaEntity)(userId,toAsanaContextItem(detailTask),null);return{handled:true,reply:formatAsanaTaskDetails(detailTask,subtasks,dependencies,timezone,now)};}
    await(deps.recordSelection??recordAsanaSelection)(userId,resources);if(resources.length===1)await(deps.recordEntity??recordAsanaEntity)(userId,toAsanaContextItem(resources[0]!),null);const noun=nounFor(responseEntity),metadataNote=responseEntity==="attachment"?"\nAttachment content isn’t retrieved in this iMessage flow; only safe metadata is shown.":responseEntity==="time_entry"?`\nTotal logged: ${resources.reduce((sum,item)=>sum+(typeof item.duration_minutes==="number"?item.duration_minutes:0),0)} minutes.`:"";return{handled:true,reply:`${responseHeader(noun,resources.length,parentProject)}\n${resources.map((resource,index)=>formatAsanaItem(resource,resources.length>1?index+1:undefined,timezone,now)).join("\n")}${metadataNote}`};
  }catch(error){logger.error("asana.read failed",{errorCode:error instanceof AsanaError?error.reason:"unknown"});return{handled:true,reply:errorReply(error)};}
}
