import { executeAction } from "../../../actions/executor";
import { createActionProposal } from "../../../actions/proposals";
import { CONFIRM_INSTRUCTION } from "../../../actions/confirmationCopy";
import { getUserTimezone } from "../../../reminders/reminders";
import { logger } from "../../../utils/logger";
import { zonedDateTimeToIso } from "../todoist/todoistFilters";
import { isAsanaReferencePhrase, recordAsanaEntity, resolveAsanaReference, toAsanaContextItem } from "./asanaContext";
import { isAsanaSelfReference, resolveAsanaPerson } from "./asanaIdentity";
import { asanaUnsupportedLimitation, extractAsanaIntent, explicitProvider, shouldConsiderAsana, type AsanaIntent, type AsanaTextGenerator } from "./asanaIntentExtract";
import { getAsanaResource, listAsanaChildren, listAsanaResources, listAsanaTasks } from "./operations";
import { searchAsanaTasksInWorkspace } from "./operations";
import { resolveAsanaTaskTitle, resolveProjectSection, taskProjectMemberships } from "./asanaTaskResolver";
import type { AsanaResource } from "./types";
import { AsanaError } from "./client";

export interface AsanaActionDeps{extract?:typeof extractAsanaIntent;generate?:AsanaTextGenerator;getTimezone?:(u:string)=>Promise<string|undefined>;listTasks?:typeof listAsanaTasks;listResources?:typeof listAsanaResources;searchWorkspace?:typeof searchAsanaTasksInWorkspace;listChildren?:typeof listAsanaChildren;getResource?:typeof getAsanaResource;resolveReference?:typeof resolveAsanaReference;resolvePerson?:typeof resolveAsanaPerson;execute?:typeof executeAction;propose?:typeof createActionProposal;recordEntity?:typeof recordAsanaEntity;now?:Date;arbitrated?:boolean}
const exact=(items:AsanaResource[],name:string)=>{const matches=items.filter(i=>typeof i.name==="string"&&i.name.trim().toLowerCase()===name.trim().toLowerCase());return matches.length===1?{item:matches[0]!,ambiguous:false}:{item:null,ambiguous:matches.length>1};};
async function workspace(userId:string,intent:AsanaIntent,deps:AsanaActionDeps){const all=await(deps.listResources??listAsanaResources)(userId,"workspaces",{count:100});if(intent.workspaceName)return exact(all,intent.workspaceName);return all.length===1?{item:all[0]!,ambiguous:false}:{item:null,ambiguous:all.length>1};}
async function target(userId:string,text:string|undefined,intent:AsanaIntent,deps:AsanaActionDeps):Promise<{items:AsanaResource[];error?:string}>{if(intent.targetAll){const refs=await import("./asanaContext").then(m=>m.loadAsanaSelection(userId));if(!refs.length)return{items:[],error:"Show me the Asana tasks first so I know exactly which set you mean."};const tasks=await Promise.all(refs.slice(0,20).map(r=>(deps.getResource??getAsanaResource)(userId,"tasks",r.id)));return{items:tasks};}if(intent.targetPhrase&&!isAsanaReferencePhrase(intent.targetPhrase)){const resolved=await resolveAsanaTaskTitle(userId,intent.targetPhrase,{listResources:deps.listResources,listTasks:deps.listTasks,searchWorkspace:deps.searchWorkspace});if(resolved.kind==="ambiguous")return{items:[],error:`I found multiple Asana tasks matching “${intent.targetPhrase}”. Which exact one do you mean?`};if(resolved.kind==="not_found")return{items:[],error:`I couldn’t find an accessible Asana task matching “${intent.targetPhrase}”.`};return{items:[await(deps.getResource??getAsanaResource)(userId,"tasks",resolved.task.gid)]};}const ref=await(deps.resolveReference??resolveAsanaReference)(userId,text,intent.targetPosition,intent.targetPhrase);if(ref.ambiguous)return{items:[],error:"I found more than one matching Asana task. Which one do you mean?"};if(ref.item)return{items:[await(deps.getResource??getAsanaResource)(userId,"tasks",ref.item.id)]};return{items:[],error:"I’m not sure which Asana task you mean — could you name it or show the list first?"};}
function fields(intent:AsanaIntent,timezone:string|undefined):Record<string,unknown>{const out:Record<string,unknown>={};if(intent.name)out.name=intent.name;if(intent.notes!==null&&intent.notes!==undefined)out.notes=intent.notes;if(intent.completed!==null&&intent.completed!==undefined)out.completed=intent.completed;if(intent.removeDue){out.due_on=null;out.due_at=null;}else if(intent.dueDate&&intent.dueTime)out.due_at=zonedDateTimeToIso(intent.dueDate,intent.dueTime,timezone);else if(intent.dueDate)out.due_on=intent.dueDate;if(intent.removeDueTime&&intent.dueDate){out.due_at=null;out.due_on=intent.dueDate;}if(intent.removeStart){out.start_on=null;out.start_at=null;}else if(intent.startDate&&intent.startTime)out.start_at=zonedDateTimeToIso(intent.startDate,intent.startTime,timezone);else if(intent.startDate)out.start_on=intent.startDate;return out;}
function customFieldValue(task:AsanaResource,intent:AsanaIntent):{field?:Record<string,unknown>;error?:string}{if(!intent.customFieldName)return{error:"Which exact Asana custom field should I change?"};const fields=Array.isArray(task.custom_fields)?task.custom_fields.filter((v):v is Record<string,unknown>=>Boolean(v)&&typeof v==="object"):[];const matches=fields.filter(f=>typeof f.name==="string"&&f.name.trim().toLowerCase()===intent.customFieldName!.trim().toLowerCase());if(matches.length!==1)return{error:matches.length>1?"That task has multiple custom fields with that name. Please use a unique field name.":`I couldn’t find a custom field called “${intent.customFieldName}” on that task.`};const field=matches[0]!;if(typeof field.gid!=="string")return{error:"Asana didn’t provide a usable identifier for that custom field."};let value=intent.customFieldValue;if(value===undefined)return{error:"What value should I set for that custom field?"};if(field.resource_subtype==="enum"&&value!==null){const options=Array.isArray(field.enum_options)?field.enum_options.filter((v):v is Record<string,unknown>=>Boolean(v)&&typeof v==="object"):[];const optionMatches=options.filter(o=>typeof o.name==="string"&&o.name.trim().toLowerCase()===String(value).trim().toLowerCase()&&o.enabled!==false);if(optionMatches.length!==1||typeof optionMatches[0]?.gid!=="string")return{error:`“${String(value)}” isn’t one unique enabled option for ${intent.customFieldName}.`};value=optionMatches[0].gid;}return{field:{[field.gid]:value}};}
function needsConfirmation(intent:AsanaIntent,count:number):boolean{return count>1||(intent.mode==="create"&&Boolean(intent.person))||intent.mode==="delete"||intent.mode==="comment"||intent.mode==="attach_url"||intent.mode==="assign"||intent.mode==="unassign"||intent.mode==="archive"||intent.mode==="unarchive"||intent.mode==="add_project"||intent.mode==="remove_project"||intent.mode==="add_follower"||intent.mode==="remove_follower";}
function lacksNamedResourceWriteScope(entity:AsanaIntent["entity"],mode:AsanaIntent["mode"]):boolean{return entity==="section"||entity==="goal"||entity==="time_entry"||(entity==="portfolio"&&mode==="delete");}
async function handleResourceMutation(userId:string,text:string|undefined,intent:AsanaIntent,deps:AsanaActionDeps):Promise<{handled:boolean;reply?:string}|null>{const entity=intent.entity;if(!entity||!["project","section","portfolio","goal","time_entry"].includes(entity))return null;const execute=deps.execute??executeAction,propose=deps.propose??createActionProposal;const title=intent.name??intent.targetPhrase??entity.replace("_"," ");let actionId=`asana.${entity}.${intent.mode==="delete"?"delete":"write"}`;let input:Record<string,unknown>={};
  if(lacksNamedResourceWriteScope(entity,intent.mode))return{handled:true,reply:`Asana’s current named OAuth scopes do not authorise ${entity.replace("_"," ")} ${intent.mode==="delete"?"deletion":"changes"}, so I won’t attempt that operation.`};
  if(entity==="time_entry"){
    if(intent.mode!=="log_time")return{handled:true,reply:"For Asana time tracking, tell me the task, date and duration you want logged."};if(!intent.durationMinutes||!intent.enteredOn)return{handled:true,reply:"What date and how many minutes should I log in Asana?"};const resolved=await target(userId,text,intent,deps);if(resolved.error)return{handled:true,reply:resolved.error};input={operation:"create",parentPath:`/tasks/${resolved.items[0]!.gid}`,data:{duration_minutes:intent.durationMinutes,entered_on:intent.enteredOn,description:intent.notes??undefined}};
  }else if(entity==="portfolio"&&["add_project","remove_project"].includes(intent.mode)){
    if(!intent.targetPhrase||!intent.projectName)return{handled:true,reply:"Name the exact Asana portfolio and project you want to change."};const ws=await workspace(userId,intent,deps);if(!ws.item)return{handled:true,reply:"Which Asana workspace contains that portfolio and project?"};const[portfolios,projects]=await Promise.all([(deps.listResources??listAsanaResources)(userId,"portfolios",{workspace:ws.item.gid,count:500}),(deps.listResources??listAsanaResources)(userId,"projects",{workspace:ws.item.gid,count:500})]);const portfolio=exact(portfolios,intent.targetPhrase),project=exact(projects,intent.projectName);if(!portfolio.item)return{handled:true,reply:portfolio.ambiguous?"I found multiple matching Asana portfolios. Which exact one?":`I couldn’t find an Asana portfolio called “${intent.targetPhrase}”.`};if(!project.item)return{handled:true,reply:project.ambiguous?"I found multiple matching Asana projects. Which exact one?":`I couldn’t find an Asana project called “${intent.projectName}”.`};actionId="asana.portfolio.membership";input={portfolioId:portfolio.item.gid,itemId:project.item.gid,operation:intent.mode==="add_project"?"addItem":"removeItem"};
  }else if(intent.mode==="create"){
    if(!intent.name)return{handled:true,reply:`What should the Asana ${entity} be called?`};const data:Record<string,unknown>={name:intent.name};if(intent.notes)data.notes=intent.notes;let parentPath:string|undefined;if(entity==="section"){if(!intent.projectName)return{handled:true,reply:"Which exact Asana project should contain the new section?"};const projects=await(deps.listResources??listAsanaResources)(userId,"projects",{count:500});const project=exact(projects,intent.projectName);if(!project.item)return{handled:true,reply:project.ambiguous?"I found multiple matching Asana projects. Which one?":`I couldn’t find an Asana project called “${intent.projectName}”.`};parentPath=`/projects/${project.item.gid}`;}else{const ws=await workspace(userId,intent,deps);if(!ws.item)return{handled:true,reply:"Which Asana workspace should I use?"};data.workspace=ws.item.gid;}input={operation:"create",data,parentPath};
  }else{
    let resources:AsanaResource[]=[];if(entity==="section"){return{handled:true,reply:"Asana’s current named OAuth scopes do not authorise section changes, so I won’t attempt that operation."};}else{const ws=await workspace(userId,intent,deps);if(!ws.item)return{handled:true,reply:ws.ambiguous?"Which Asana workspace should I use?":"I couldn’t find that Asana workspace."};const plural=entity==="project"?"projects":entity==="portfolio"?"portfolios":"goals";resources=await(deps.listResources??listAsanaResources)(userId,plural,{workspace:ws.item.gid,count:500});}const match=exact(resources,intent.targetPhrase??intent.name??"");if(!match.item)return{handled:true,reply:match.ambiguous?`I found multiple matching Asana ${entity}s. Which one?`:`I couldn’t find that Asana ${entity}.`};if(intent.mode==="delete")input={resourceId:match.item.gid,title:typeof match.item.name==="string"?match.item.name:title};else{const data:Record<string,unknown>={};if(intent.mode==="archive")data.archived=true;if(intent.mode==="unarchive")data.archived=false;if(intent.name)data.name=intent.name;if(intent.notes)data.notes=intent.notes;if(!Object.keys(data).length)return{handled:true,reply:`What should I change on that Asana ${entity}?`};input={operation:"update",resourceId:match.item.gid,data};}
  }
  const preview=intent.mode==="delete"?`I’ll permanently delete the Asana ${entity} “${title}”. This can’t be undone. ${CONFIRM_INSTRUCTION}`:entity==="time_entry"?`I’ll log ${intent.durationMinutes} minutes on ${intent.enteredOn} in Asana. ${CONFIRM_INSTRUCTION}`:`I’ll ${intent.mode==="create"?"create":"update"} the Asana ${entity} “${title}”. ${CONFIRM_INSTRUCTION}`;await propose(userId,{provider:"asana",actionId,riskLevel:"write",confirmationRequired:true,input,previewText:preview});return{handled:true,reply:preview};}
export async function handleAsanaWrite(userId:string,text:string|undefined,deps:AsanaActionDeps={}):Promise<{handled:boolean;reply?:string}>{if(!deps.arbitrated&&!shouldConsiderAsana(text))return{handled:false};try{const timezone=await(deps.getTimezone??getUserTimezone)(userId);const intent=await(deps.extract??extractAsanaIntent)({text:text??"",now:(deps.now??new Date()).toISOString(),timezone,providerContext:deps.arbitrated?"asana":undefined,generate:deps.generate});if(!intent||intent.provider!=="asana"||intent.mode==="read"||intent.mode==="not_asana")return{handled:false};if(explicitProvider(text)==="todoist")return{handled:false};let actionId="asana.task.update";let input:Record<string,unknown>={};let titles:string[]=[];
  const limitation=asanaUnsupportedLimitation(intent.entity);if(limitation)return{handled:true,reply:limitation};
  const resourceResult=await handleResourceMutation(userId,text,intent,deps);if(resourceResult)return resourceResult;
  if(intent.mode==="create"){
    if(!intent.name)return{handled:true,reply:`What should the Asana ${intent.entity==="subtask"?"subtask":"task"} be called?`};const ws=await workspace(userId,intent,deps);if(!ws.item)return{handled:true,reply:ws.ambiguous?"Which Asana workspace should I use?":"I couldn’t find that Asana workspace."};const taskFields=fields(intent,timezone);taskFields.workspace=ws.item.gid;if(intent.person){const person=await(deps.resolvePerson??resolveAsanaPerson)(userId,ws.item.gid,intent.person);if(person.kind==="self_unavailable")return{handled:true,reply:"I couldn’t verify your authenticated Asana identity, so I didn’t create an assigned task."};if(person.kind==="ambiguous")return{handled:true,reply:`I found multiple people named that: ${person.names.join(", ")}. Please use their exact email.`};if(person.kind==="not_found")return{handled:true,reply:`I couldn’t find “${intent.person}” among accessible Asana users.`};taskFields.assignee=person.user.gid;}if(intent.entity==="subtask"){const parent=await target(userId,text,intent,deps);if(parent.error)return{handled:true,reply:parent.error};taskFields.parent=parent.items[0]!.gid;}if(intent.projectName){const projects=await(deps.listResources??listAsanaResources)(userId,"projects",{workspace:ws.item.gid,count:500});const project=exact(projects,intent.projectName);if(!project.item)return{handled:true,reply:project.ambiguous?"I found several Asana projects with that name. Which one?":`I couldn’t find an Asana project called “${intent.projectName}”.`};taskFields.projects=[project.item.gid];if(intent.entity!=="subtask"){const existing=(await(deps.listTasks??listAsanaTasks)(userId,{project:project.item.gid,count:500})).filter(task=>typeof task.name==="string"&&task.name.trim().toLowerCase()===intent.name!.trim().toLowerCase());if(existing.length>1)return{handled:true,reply:`I found multiple tasks called “${intent.name}” in ${intent.projectName}. I won’t create another until you clarify.`};if(existing.length===1){await(deps.recordEntity??recordAsanaEntity)(userId,toAsanaContextItem(existing[0]!),"existing");return{handled:true,reply:`“${intent.name}” already exists in ${intent.projectName}, so I didn’t create a duplicate.`};}}}actionId="asana.task.create";input=taskFields;titles=[intent.name];
  }else{
    const resolved=await target(userId,text,intent,deps);if(resolved.error)return{handled:true,reply:resolved.error};titles=resolved.items.map(t=>typeof t.name==="string"?t.name:"Untitled");const taskIds=resolved.items.map(t=>t.gid);
    if(intent.mode==="delete"){actionId="asana.task.delete";input={taskIds,titles};}
    else if(intent.mode==="move"){if(resolved.items.length!==1)return{handled:true,reply:"Move one Asana task at a time so I can verify its project and section."};if(!intent.sectionName)return{handled:true,reply:"Which exact Asana section should I move that task to?"};const projects=taskProjectMemberships(resolved.items[0]!);if(!projects.length)return{handled:true,reply:"That Asana task isn’t in a project, so it can’t be moved to a project section."};const sectionMatches:AsanaResource[]=[];for(const project of projects){const section=await resolveProjectSection(userId,project.gid,intent.sectionName,{listTasks:deps.listTasks});if(section.kind==="ambiguous")return{handled:true,reply:`I found duplicate “${intent.sectionName}” sections in that Asana project. Which one do you mean?`};if(section.kind==="resolved")sectionMatches.push({...section.section,project});}if(sectionMatches.length===0)return{handled:true,reply:`I couldn’t find an “${intent.sectionName}” section in that task’s Asana project.`};if(sectionMatches.length>1)return{handled:true,reply:`I found an “${intent.sectionName}” section in more than one of that task’s projects. Which project do you mean?`};actionId="asana.task.relationship";input={taskIds,titles,relationshipAction:"moveToSection",relationshipInput:{section:sectionMatches[0]!.gid,project:(sectionMatches[0]!.project as AsanaResource).gid,sectionName:intent.sectionName}};}
    else if(intent.mode==="comment"){if(!intent.notes)return{handled:true,reply:"What comment should I post?"};actionId="asana.task.comment";input={taskIds,text:intent.notes,titles};}
    else if(["assign","unassign"].includes(intent.mode)){if(intent.mode==="unassign")input={taskIds,titles,fields:{assignee:null}};else{if(!intent.person)return{handled:true,reply:"Who should I assign it to? Please give their exact Asana name or email."};const selfReference=isAsanaSelfReference(intent.person);const ws=selfReference?{item:{gid:""} as AsanaResource,ambiguous:false}:await workspace(userId,intent,deps);if(!ws.item)return{handled:true,reply:"Which Asana workspace is that person in?"};const person=await(deps.resolvePerson??resolveAsanaPerson)(userId,ws.item.gid,intent.person);if(person.kind==="self_unavailable")return{handled:true,reply:"I couldn’t verify your authenticated Asana identity, so I didn’t change the assignee."};if(person.kind==="ambiguous")return{handled:true,reply:`I found multiple people named that: ${person.names.join(", ")}. Please use their exact email.`};if(person.kind==="not_found")return{handled:true,reply:`I couldn’t find “${intent.person}” among accessible Asana users.`};input={taskIds,titles,fields:{assignee:person.user.gid}};}}
    else if(["add_project","remove_project"].includes(intent.mode)){if(!intent.projectName)return{handled:true,reply:"Which exact Asana project should I use?"};const ws=await workspace(userId,intent,deps);if(!ws.item)return{handled:true,reply:"Which Asana workspace contains that project?"};const projects=await(deps.listResources??listAsanaResources)(userId,"projects",{workspace:ws.item.gid,count:500});const project=exact(projects,intent.projectName);if(!project.item)return{handled:true,reply:project.ambiguous?"I found multiple Asana projects with that name. Which exact one?":`I couldn’t find an Asana project called “${intent.projectName}”.`};actionId="asana.task.relationship";input={taskIds,titles,relationshipAction:intent.mode==="add_project"?"addProject":"removeProject",relationshipInput:{project:project.item.gid}};
    }else if(["add_follower","remove_follower"].includes(intent.mode)){if(!intent.person)return{handled:true,reply:"Who should I use? Please give their exact Asana name or email."};const ws=await workspace(userId,intent,deps);if(!ws.item)return{handled:true,reply:"Which Asana workspace is that person in?"};const person=await(deps.resolvePerson??resolveAsanaPerson)(userId,ws.item.gid,intent.person);if(person.kind==="self_unavailable")return{handled:true,reply:"I couldn’t verify your authenticated Asana identity, so I didn’t change the followers."};if(person.kind==="ambiguous")return{handled:true,reply:`I found multiple people named that: ${person.names.join(", ")}. Please use their exact email.`};if(person.kind==="not_found")return{handled:true,reply:`I couldn’t find “${intent.person}” among accessible Asana users.`};actionId="asana.task.relationship";input={taskIds,titles,relationshipAction:intent.mode==="add_follower"?"addFollowers":"removeFollowers",relationshipInput:{followers:[person.user.gid]}};
    }else if(["add_dependency","remove_dependency"].includes(intent.mode)){if(!intent.relatedTaskPhrase)return{handled:true,reply:"Tell me the exact blocker task as well as the task being blocked, so I don’t link the wrong work."};const related=await resolveAsanaTaskTitle(userId,intent.relatedTaskPhrase,{listResources:deps.listResources,listTasks:deps.listTasks,searchWorkspace:deps.searchWorkspace});if(related.kind!=="resolved")return{handled:true,reply:related.kind==="ambiguous"?"I found multiple possible blocker tasks. Which exact one?":`I couldn’t find an Asana task called “${intent.relatedTaskPhrase}”.`};actionId="asana.task.relationship";input={taskIds,titles,relationshipAction:intent.mode==="add_dependency"?"addDependencies":"removeDependencies",relationshipInput:{dependencies:[related.task.gid]}};}
    else if(["add_tag","remove_tag"].includes(intent.mode)){if(!intent.tagName)return{handled:true,reply:"Which exact Asana tag should I use?"};const ws=await workspace(userId,intent,deps);if(!ws.item)return{handled:true,reply:"Which Asana workspace contains that tag?"};const tags=await(deps.listResources??listAsanaResources)(userId,"tags",{workspace:ws.item.gid,count:500});const tag=exact(tags,intent.tagName);if(!tag.item)return{handled:true,reply:tag.ambiguous?"I found multiple matching tags. Which exact one?":`I couldn’t find an Asana tag called “${intent.tagName}”.`};actionId="asana.task.relationship";input={taskIds,titles,relationshipAction:intent.mode==="add_tag"?"addTag":"removeTag",relationshipInput:{tag:tag.item.gid}};
    }else if(intent.mode==="attach_url"){if(!intent.attachmentUrl)return{handled:true,reply:"Which HTTPS URL should I attach to that Asana task?"};actionId="asana.task.attachUrl";input={taskIds,titles,relationshipInput:{url:intent.attachmentUrl,name:intent.name??undefined}};
    }else{const taskFields=fields(intent,timezone);if(intent.removeDueTime&&!intent.dueDate){const source=resolved.items[0];const retained=typeof source?.due_on==="string"?source.due_on:typeof source?.due_at==="string"?new Intl.DateTimeFormat("en-CA",{timeZone:timezone??"UTC",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date(source.due_at)):null;if(!retained)return{handled:true,reply:"That Asana task doesn’t have a due time to remove."};taskFields.due_at=null;taskFields.due_on=retained;}if(intent.mode==="complete")taskFields.completed=true;if(intent.mode==="reopen")taskFields.completed=false;if(intent.mode==="set_custom_field"){if(resolved.items.length!==1)return{handled:true,reply:"Change one task’s custom field at a time so I can validate its definition."};const custom=customFieldValue(resolved.items[0]!,intent);if(custom.error)return{handled:true,reply:custom.error};taskFields.custom_fields=custom.field;}if(intent.mode==="log_time")return{handled:true,reply:"I need the date and duration for the Asana time entry before logging it."};if(!Object.keys(taskFields).length)return{handled:true,reply:"What would you like me to change on that Asana task?"};input={taskIds,titles,fields:taskFields};}
  }
  const confirm=needsConfirmation(intent,Array.isArray(input.taskIds)?input.taskIds.length:1);if(confirm){const count=Array.isArray(input.taskIds)?input.taskIds.length:1;const targetText=titles.slice(0,3).map(t=>`“${t}”`).join(", ");const consequence=intent.mode==="delete"?"permanently delete":intent.mode==="comment"?"post a comment on":intent.mode.includes("follower")?"change followers on":intent.mode==="create"&&intent.person?"create and assign":"change";await(deps.propose??createActionProposal)(userId,{provider:"asana",actionId,riskLevel:intent.mode==="comment"?"send":"write",confirmationRequired:true,input,previewText:`I’ll ${consequence} ${count===1?targetText:`${count} Asana tasks`}. ${intent.mode==="delete"?"This can’t be undone. ":""}${CONFIRM_INSTRUCTION}`});return{handled:true,reply:`I’ll ${consequence} ${count===1?targetText:`${count} Asana tasks`}. ${intent.mode==="delete"?"This can’t be undone. ":""}${CONFIRM_INSTRUCTION}`};}
  const result=await(deps.execute??executeAction)(userId,actionId,{input,userConfirmed:true});if(result.ok&&result.receipt?.asanaResourceIds?.[0]){try{const observed=await(deps.getResource??getAsanaResource)(userId,"tasks",result.receipt.asanaResourceIds[0]);await(deps.recordEntity??recordAsanaEntity)(userId,toAsanaContextItem(observed),intent.mode);}catch{}}return{handled:true,reply:result.userMessage};
 }catch(error){const providerError=error instanceof AsanaError?error:null;logger.error("asana.write failed",{operation:"resolve_or_execute",errorCode:providerError?.reason??"validation_error",httpStatus:providerError?.status??null,endpoint:"typed_asana_operation",category:providerError?"provider":"validation"});return{handled:true,reply:"I couldn’t make that Asana change just now. Nothing unverified has been reported as done."};}}
