import { z } from "zod";
import { generateAnthropicText } from "../../../ai/anthropicClient";

const text=(n:number)=>z.string().trim().min(1).max(n).nullable().optional();
const date=z.string().regex(/^\d{4}-\d{2}-\d{2}$/).nullable().optional();
const time=z.string().regex(/^\d{2}:\d{2}$/).nullable().optional();
const entity=z.enum(["task","subtask","project","section","team","portfolio","goal","comment","attachment","time_entry","dependency","custom_field","tag","follower","membership","workspace","user","template","webhook","role","ooo_entry","job","export","timesheet","time_period","project_brief","project_status","allocation","budget"]);
const modes=["read","create","update","archive","unarchive","complete","reopen","delete","move","assign","unassign","comment","attach_url","add_project","remove_project","add_follower","remove_follower","add_dependency","remove_dependency","add_tag","remove_tag","set_custom_field","log_time","not_asana"] as const;
export const AsanaIntentSchema=z.object({
  provider:z.enum(["asana","todoist","calendar","reminder","gmail","memory","unknown"]),mode:z.enum(modes),
  entity:entity.nullable().optional(),targetPhrase:text(300),relatedTaskPhrase:text(300),targetPosition:z.number().int().min(1).max(20).nullable().optional(),targetAll:z.boolean().nullable().optional(),name:text(500),notes:text(5000),attachmentUrl:z.string().url().max(2000).nullable().optional(),projectName:text(200),portfolioName:text(200),sectionName:text(200),workspaceName:text(200),person:text(320),tagName:text(120),customFieldName:text(120),customFieldValue:z.union([z.string(),z.number(),z.boolean(),z.null()]).optional(),query:text(200),archived:z.boolean().nullable().optional(),dueDate:date,dueTime:time,startDate:date,startTime:time,removeDue:z.boolean().nullable().optional(),removeDueTime:z.boolean().nullable().optional(),removeStart:z.boolean().nullable().optional(),completed:z.boolean().nullable().optional(),count:z.number().int().min(1).max(50).nullable().optional(),durationMinutes:z.number().int().min(1).max(1440).nullable().optional(),enteredOn:date,
});
export type AsanaIntent=z.infer<typeof AsanaIntentSchema>;
export type AsanaTextGenerator=(p:{system:string;messages:{role:"user"|"assistant";content:string}[];maxTokens?:number})=>Promise<string>;
export function buildAsanaIntentPrompt(now:string,timezone:string|undefined,providerContext?:"asana"):string{const shape={provider:"asana|todoist|calendar|reminder|gmail|memory|unknown",mode:modes.join("|"),entity:[...entity.options,"null"].join("|"),targetPhrase:null,relatedTaskPhrase:null,targetPosition:null,targetAll:null,name:null,notes:null,attachmentUrl:null,projectName:null,portfolioName:null,sectionName:null,workspaceName:null,person:null,tagName:null,customFieldName:null,customFieldValue:null,query:null,archived:null,dueDate:null,dueTime:null,startDate:null,startTime:null,removeDue:null,removeDueTime:null,removeStart:null,completed:null,count:null,durationMinutes:null,enteredOn:null};return ["Extract one provider intent. Never answer or perform it.",`Current local timestamp: ${now}; IANA timezone: ${timezone??"UTC"}.`,`Return JSON only matching: ${JSON.stringify(shape)}`,"Provider rules: explicit Asana wins. Explicit Todoist wins. Meetings/reserving time are calendar. 'Remind me' is reminder. Email/draft/reply is Gmail. Remember/forget is memory. A generic task/project request with neither explicit provider nor compatible context is unknown, never Asana by default.",providerContext==="asana"?"Durable entity arbitration verified that the referenced entity belongs to Asana. Use provider asana for this pronoun or ordinal follow-up; still extract read versus mutation semantically.":"No provider context was supplied.","Resolve relative dates from the supplied local timestamp. A date without a time must keep time null. Never invent a person, project, section, field, date, count or provider.","Pronouns, possessive pronouns and ordinals are references: set targetPosition for ordinals, otherwise leave targetPhrase null. Never put 'it', 'its', 'that', 'this', 'the task', or 'the one' in targetPhrase. For details about a task named by the user, preserve the complete requested task title in targetPhrase; do not put it in query and do not reduce it to keywords.","For a move, put the task title or pronoun reference in targetPhrase and the destination section name in sectionName. Never model a section as a task update field. For projects inside a named portfolio, put the portfolio name in portfolioName. Archived project reads set archived true.","Comments are external communication. Assignment/follower fields use person. A subtask create uses name for the new subtask and targetPhrase for its exact parent. A dependency uses relatedTaskPhrase for the blocker. 'Remove the time but keep Friday' sets removeDueTime, not removeDue. Removing a start date sets removeStart.","If provider is not asana return mode not_asana."].join("\n");}
export function parseAsanaIntent(raw:string):AsanaIntent|null{const a=raw.indexOf("{"),b=raw.lastIndexOf("}");if(a<0||b<=a)return null;try{const parsed=AsanaIntentSchema.safeParse(JSON.parse(raw.slice(a,b+1)));return parsed.success?parsed.data:null;}catch{return null;}}
export async function extractAsanaIntent(input:{text:string;now:string;timezone?:string;providerContext?:"asana";generate?:AsanaTextGenerator}):Promise<AsanaIntent|null>{try{const raw=await(input.generate??generateAnthropicText)({system:buildAsanaIntentPrompt(input.now,input.timezone,input.providerContext),messages:[{role:"user",content:input.text}],maxTokens:700});return parseAsanaIntent(raw);}catch{return null;}}
export function explicitProvider(textValue:string|undefined):"asana"|"todoist"|null{const value=(textValue??"").toLowerCase();const a=/\basana\b/.test(value),t=/\btodoist\b/.test(value);return a&&!t?"asana":t&&!a?"todoist":null;}
export function asanaUnsupportedLimitation(entity:AsanaIntent["entity"]):string|null{if(!entity)return null;if(entity==="section")return"Asana’s selected named scopes do not expose section resources. Hula can still move a task to a populated section discovered through authorised task memberships, but it cannot list empty sections.";if(["project_brief","project_status","time_period"].includes(entity))return"Asana does not currently provide a named OAuth scope for that resource, so Hula won’t attempt it without Full permissions.";if(["goal","time_entry"].includes(entity))return null;if(entity==="export")return"Asana organisation exports are admin/service-account operations and aren’t available through Hula’s ordinary OAuth connection.";if(["webhook","role","ooo_entry","job","template","timesheet","allocation","budget","membership"].includes(entity))return"That Asana administration or planning surface isn’t enabled in Hula’s selected conversational OAuth capabilities.";return null;}
export function shouldConsiderAsana(textValue:string|undefined):boolean{const value=(textValue??"").trim().toLowerCase();if(!value)return false;if(/\bslack\b|#[a-z0-9_-]+/.test(value)||(/\b(?:post|message|reply|react|pin|unpin)\b/.test(value)&&/\b[a-z0-9]+-[a-z0-9-]+\b/.test(value)))return false;if(/\basana\b/.test(value))return true;return /\b(?:task|subtask|project|section|portfolio|goal|dependency|blocked|follower|custom field|time entr(?:y|ies)|template|webhook|role|out of office|export|timesheet|allocation|budget)s?\b/.test(value);}
