import { Router } from "express";
import { requireClerkAuth } from "../auth/clerk";
import { getPrisma } from "../db/prisma";
import { sanitizeAppReturnUrl } from "../integrations/appReturnUrl";
import { recordIntegrationEvent, upsertIntegrationConnection } from "../integrations/connections";
import { storeCredentialSecrets } from "../integrations/credentials";
import { consumeOAuthState, createOAuthState } from "../integrations/oauthState";
import { resolveOAuthCallbackReplay } from "../integrations/oauthReplay";
import { AsanaOAuthConfigError, buildAsanaAuthorizationUrl, capabilitiesFromAsanaScopes, createAsanaPkce, exchangeAsanaToken, getAsanaOAuthConfig } from "../integrations/providers/asana/oauth";
import { ASANA_PROVIDER } from "../integrations/providers/asana/types";
import { getOrCreateUserByClerkId } from "../users/store";
import { logger } from "../utils/logger";

export const asanaRouter=Router();
const queryValue=(value:unknown)=>typeof value==="string"?value:undefined;
const resultPage=(ok:boolean,returnUrl:string|null)=>`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Asana ${ok?"connected":"connection failed"}</title></head><body style="background:#080a16;color:#f6f8ff;font-family:system-ui;text-align:center;padding:64px 24px"><h1>${ok?"Asana connected":"Couldn’t connect Asana"}</h1><p>${ok?"You can return to Hula and text as usual.":"Return to Hula and try again."}</p>${returnUrl?`<a style="color:#f06a6a" href="${returnUrl.replace(/["<>]/g,"")}">Return to Hula</a>`:""}</body></html>`;

asanaRouter.post("/v1/me/integrations/asana/connect",requireClerkAuth,async(req,res)=>{try{const config=getAsanaOAuthConfig();const user=await getOrCreateUserByClerkId(req.clerkUserId as string);const pkce=createAsanaPkce();const appReturnUrl=sanitizeAppReturnUrl((req.body as {appReturnUrl?:unknown}|undefined)?.appReturnUrl);const pending=await createOAuthState({userId:user.id,provider:ASANA_PROVIDER,redirectUri:config.redirectUri,scopes:config.scopes,codeVerifier:pkce.verifier,appReturnUrl});res.json({provider:ASANA_PROVIDER,authorizationUrl:buildAsanaAuthorizationUrl({config,state:pending.state,challenge:pkce.challenge}),expiresAt:pending.expiresAt.toISOString()});}catch(error){if(error instanceof AsanaOAuthConfigError){res.status(400).json({error:"asana_not_configured"});return;}logger.error("asana.connect failed",{reason:error instanceof Error?error.name:"unknown"});res.status(500).json({error:"asana_connect_failed"});}});

asanaRouter.get("/v1/integrations/asana/callback",async(req,res)=>{const code=queryValue(req.query.code),state=queryValue(req.query.state);if(!code||!state||queryValue(req.query.error)){res.status(400).type("html").send(resultPage(false,null));return;}let returnUrl:string|null=null;try{const consumed=await consumeOAuthState(state,ASANA_PROVIDER);if(!consumed){const replay=await resolveOAuthCallbackReplay(state,ASANA_PROVIDER);if(replay){res.type("html").send(resultPage(true,sanitizeAppReturnUrl(replay.appReturnUrl)));return;}res.status(400).type("html").send(resultPage(false,null));return;}returnUrl=sanitizeAppReturnUrl(consumed.appReturnUrl);const tokens=await exchangeAsanaToken({config:getAsanaOAuthConfig(),code,verifier:consumed.codeVerifier??undefined});const scopes=tokens.scopes.length?tokens.scopes:consumed.scopes;const capabilities=capabilitiesFromAsanaScopes(scopes);if(!capabilities.includes("work.read")){res.status(403).type("html").send(resultPage(false,returnUrl));return;}await upsertIntegrationConnection(consumed.userId,{provider:ASANA_PROVIDER,status:"connected",providerAccountId:tokens.account?.gid??null,providerAccountEmail:tokens.account?.email??null,displayName:tokens.account?.name??"Asana",grantedScopes:scopes,requestedScopes:consumed.scopes,capabilities});const connection=await getPrisma().integrationConnection.findUnique({where:{userId_provider:{userId:consumed.userId,provider:ASANA_PROVIDER}},select:{id:true}});if(!connection)throw new Error("connection missing");await storeCredentialSecrets(connection.id,{accessToken:tokens.accessToken,refreshToken:tokens.refreshToken,accessTokenExpiresAt:new Date(Date.now()+tokens.expiresIn*1000),scopes});await recordIntegrationEvent({userId:consumed.userId,provider:ASANA_PROVIDER,eventType:"oauth.connected",connectionId:connection.id,safeSummary:{scopeCount:scopes.length,capabilityCount:capabilities.length}});res.type("html").send(resultPage(true,returnUrl));}catch(error){logger.error("asana.callback failed",{reason:error instanceof Error?error.name:"unknown"});res.status(500).type("html").send(resultPage(false,returnUrl));}});
