import { Router } from "express";
import { requireClerkAuth } from "../auth/clerk";
import { getPrisma } from "../db/prisma";
import { sanitizeAppReturnUrl } from "../integrations/appReturnUrl";
import { disconnectIntegrationConnection, recordIntegrationEvent, upsertIntegrationConnection } from "../integrations/connections";
import { readCredentialSecrets, storeCredentialSecrets } from "../integrations/credentials";
import { createOAuthState, consumeOAuthState } from "../integrations/oauthState";
import { resolveOAuthCallbackReplay } from "../integrations/oauthReplay";
import { buildNotionAuthorizationUrl, capabilitiesFromNotionScopes, exchangeNotionCode, getNotionOAuthConfig, introspectNotionToken, NotionOAuthConfigError, revokeNotionToken } from "../integrations/providers/notion/oauth";
import { NOTION_PROVIDER } from "../integrations/providers/notion/types";
import { getOrCreateUserByClerkId } from "../users/store";
import { logger } from "../utils/logger";

export const notionRouter=Router();
const q=(v:unknown)=>typeof v==="string"?v:undefined;
const page=(ok:boolean,returnUrl:string|null)=>`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Notion ${ok?"connected":"connection failed"}</title></head><body style="background:#080a16;color:#f6f8ff;font-family:system-ui;text-align:center;padding:64px 24px"><h1>${ok?"Notion connected":"Couldn’t connect Notion"}</h1><p>${ok?"You can return to Hula and text as usual.":"Return to Hula and try again."}</p>${returnUrl?`<a style="color:#fff" href="${returnUrl.replace(/["<>]/g,"")}">Return to Hula</a>`:""}</body></html>`;

notionRouter.post("/v1/me/integrations/notion/connect",requireClerkAuth,async(req,res)=>{try{const config=getNotionOAuthConfig(),user=await getOrCreateUserByClerkId(req.clerkUserId as string),appReturnUrl=sanitizeAppReturnUrl((req.body as {appReturnUrl?:unknown}|undefined)?.appReturnUrl);const pending=await createOAuthState({userId:user.id,provider:NOTION_PROVIDER,redirectUri:config.redirectUri,scopes:["content:read","content:write","comments:read","comments:write","user:read"],codeVerifier:null,appReturnUrl});res.json({provider:NOTION_PROVIDER,authorizationUrl:buildNotionAuthorizationUrl({config,state:pending.state}),expiresAt:pending.expiresAt.toISOString()});}catch(error){if(error instanceof NotionOAuthConfigError){res.status(400).json({error:"notion_not_configured"});return;}logger.error("notion.connect failed",{reason:error instanceof Error?error.name:"unknown"});res.status(500).json({error:"notion_connect_failed"});}});

notionRouter.get("/v1/integrations/notion/callback",async(req,res)=>{const code=q(req.query.code),state=q(req.query.state);if(!code||!state||q(req.query.error)){res.status(400).type("html").send(page(false,null));return;}let returnUrl:string|null=null;try{const consumed=await consumeOAuthState(state,NOTION_PROVIDER);if(!consumed){const replay=await resolveOAuthCallbackReplay(state,NOTION_PROVIDER);if(replay){res.type("html").send(page(true,sanitizeAppReturnUrl(replay.appReturnUrl)));return;}res.status(400).type("html").send(page(false,null));return;}returnUrl=sanitizeAppReturnUrl(consumed.appReturnUrl);const config=getNotionOAuthConfig(),tokens=await exchangeNotionCode(config,code),grant=await introspectNotionToken(config,tokens.accessToken);if(!grant.active)throw new Error("inactive grant");const capabilities=capabilitiesFromNotionScopes(grant.scopes);if(!capabilities.includes("content.read")){res.status(403).type("html").send(page(false,returnUrl));return;}const normalizedScopes=[...grant.scopes,...(capabilities.includes("content.read")?["content:read"]:[]),...(capabilities.includes("content.write")?["content:write"]:[]),...(capabilities.includes("users.read")?["user:read"]:[])];await upsertIntegrationConnection(consumed.userId,{provider:NOTION_PROVIDER,status:"connected",providerAccountId:tokens.botId,providerAccountEmail:tokens.ownerEmail,displayName:tokens.workspaceName??tokens.ownerName??"Notion",grantedScopes:normalizedScopes,requestedScopes:consumed.scopes,capabilities});const connection=await getPrisma().integrationConnection.findUnique({where:{userId_provider:{userId:consumed.userId,provider:NOTION_PROVIDER}},select:{id:true}});if(!connection)throw new Error("connection missing");await storeCredentialSecrets(connection.id,{accessToken:tokens.accessToken,refreshToken:tokens.refreshToken,scopes:normalizedScopes});await recordIntegrationEvent({userId:consumed.userId,provider:NOTION_PROVIDER,eventType:"oauth.connected",connectionId:connection.id,safeSummary:{scopeCount:grant.scopes.length,capabilityCount:capabilities.length}});res.type("html").send(page(true,returnUrl));}catch(error){logger.error("notion.callback failed",{reason:error instanceof Error?error.name:"unknown"});res.status(500).type("html").send(page(false,returnUrl));}});

notionRouter.post("/v1/me/integrations/notion/disconnect",requireClerkAuth,async(req,res)=>{try{const user=await getOrCreateUserByClerkId(req.clerkUserId as string),connection=await getPrisma().integrationConnection.findUnique({where:{userId_provider:{userId:user.id,provider:NOTION_PROVIDER}},select:{id:true,status:true}});if(!connection||connection.status==="disconnected"){res.json({ok:true,changed:false});return;}const credential=await readCredentialSecrets(connection.id);if(credential?.accessToken){try{await revokeNotionToken(getNotionOAuthConfig(),credential.accessToken);}catch(error){logger.error("notion.revoke failed",{reason:error instanceof Error?error.name:"unknown"});res.status(502).json({error:"notion_revoke_failed"});return;}}const changed=await disconnectIntegrationConnection(user.id,NOTION_PROVIDER);await recordIntegrationEvent({userId:user.id,provider:NOTION_PROVIDER,eventType:"oauth.disconnected",connectionId:connection.id,safeSummary:{remoteRevocationAttempted:Boolean(credential?.accessToken)}});res.json({ok:true,changed});}catch(error){logger.error("notion.disconnect failed",{reason:error instanceof Error?error.name:"unknown"});res.status(500).json({error:"notion_disconnect_failed"});}});
