import { createActionProposal } from "../../../actions/proposals";
import { executeAction } from "../../../actions/executor";
import { CONFIRM_INSTRUCTION } from "../../../actions/confirmationCopy";
import { getUserTimezone } from "../../../reminders/reminders";
import { logger } from "../../../utils/logger";
import { recordNotionEntity, recordNotionSelection, resolveNotionReference, type NotionRef } from "./context";
import { notionPlainText, notionTitle, propertyText, renderBlock, richText } from "./display";
import { extractNotionIntent, notionLimitation, shouldConsiderNotion, type NotionGenerator, type NotionIntent } from "./intent";
import { notionOps } from "./operations";
import { NotionError } from "./client";
import type { NotionObject } from "./types";
import { resolveNotionResource, resolveQueryableDataSource, type NotionResourceResolution, type ResolvedNotionResource } from "./resourceResolver";

export interface NotionConversationDeps {extract?:typeof extractNotionIntent;generate?:NotionGenerator;getTimezone?:typeof getUserTimezone;search?:typeof notionOps.search;page?:typeof notionOps.page;database?:typeof notionOps.database;dataSource?:typeof notionOps.dataSource;query?:typeof notionOps.query;children?:typeof notionOps.children;comments?:typeof notionOps.comments;users?:typeof notionOps.users;me?:typeof notionOps.me;createPage?:typeof notionOps.createPage;updatePage?:typeof notionOps.updatePage;appendBlocks?:typeof notionOps.appendBlocks;updateDataSource?:typeof notionOps.updateDataSource;recordSelection?:typeof recordNotionSelection;recordEntity?:typeof recordNotionEntity;resolve?:typeof resolveNotionReference;resolveResource?:typeof resolveNotionResource;resolveQueryable?:typeof resolveQueryableDataSource;propose?:typeof createActionProposal;execute?:typeof executeAction;now?:Date;arbitrated?:boolean}
const errorReply=(e:unknown)=>e instanceof NotionError&&e.code==="not_connected"?"Your Notion workspace isn’t connected. Connect it in Hula’s Integrations screen first.":e instanceof NotionError&&(e.code==="forbidden"||e.code==="not_found")?"I can’t access that Notion content. It may be private or not shared with Hula.":e instanceof NotionError&&(e.code==="unauthorized"||e.code==="reconnect_required")?"Your Notion connection needs to be reconnected before I can do that.":e instanceof NotionError&&e.code==="rate_limited"?"Notion is rate-limiting requests right now. Please try again shortly.":"I couldn’t reach Notion reliably just now. Please try again in a moment.";
const pageKind=(o:NotionObject)=>o.object==="page"&&o.parent&&typeof o.parent==="object"&&(o.parent as Record<string,unknown>).type==="data_source_id"?"record":"page";
const objectType=(o:NotionObject)=>o.object==="data_source"?"data source":o.object==="database"?"database":o.object==="page"?pageKind(o):o.object??"page";
const titleLine=(o:NotionObject,i?:number)=>`${i?`${i}. `:""}${notionTitle(o)} — ${objectType(o)}`;
const textBlock=(type:string,text:string,extra:Record<string,unknown>={})=>({object:"block",type,[type]:{rich_text:[{type:"text",text:{content:notionPlainText(text,2000)}}],...extra}});
const resolverDeps=(deps:NotionConversationDeps)=>({search:deps.search,children:deps.children,database:deps.database,dataSource:deps.dataSource});
const resolutionError=(target:string,resolution:NotionResourceResolution)=>resolution.kind==="ambiguous"?`I found several accessible Notion resources matching “${notionPlainText(target)}”: ${resolution.candidates.map(candidate=>`“${notionPlainText(candidate.ref.title)}”${candidate.ref.parentTitle?` in “${notionPlainText(candidate.ref.parentTitle)}”`:""}`).join(", ")}. Which exact one do you mean?`:`I couldn’t find accessible Notion content matching “${notionPlainText(target)}”.`;
async function resolveTarget(userId:string,intent:NotionIntent,deps:NotionConversationDeps):Promise<{ref:NotionRef|null;object:NotionObject|null;resource?:ResolvedNotionResource;error?:string}>{
  if(intent.position||!intent.target){const ref=await(deps.resolve??resolveNotionReference)(userId,intent.target??undefined,intent.position);if(ref)return{ref,object:null};}
  if(!intent.target)return{ref:null,object:null,error:"Which Notion page, record, database, data source or block do you mean?"};
  const resolution=await(deps.resolveResource??resolveNotionResource)(userId,intent.target,resolverDeps(deps));
  if(resolution.kind!=="resolved")return{ref:null,object:null,error:resolutionError(intent.target,resolution)};
  return{ref:resolution.resource.ref,object:resolution.resource.object,resource:resolution.resource};
}
async function recursiveBlocks(userId:string,id:string,deps:NotionConversationDeps,depth=0,seen={count:0}):Promise<string[]>{if(depth>4||seen.count>=200)return[];const blocks=await(deps.children??notionOps.children)(userId,id),lines:string[]=[];for(const block of blocks){if(seen.count++>=200)break;const rendered=renderBlock(block);if(rendered)lines.push(rendered);if(block.has_children===true&&typeof block.id==="string")lines.push(...await recursiveBlocks(userId,block.id,deps,depth+1,seen));}return lines;}
function properties(page:NotionObject):string[]{const props=page.properties&&typeof page.properties==="object"?page.properties as Record<string,unknown>:{};return Object.entries(props).map(([name,value])=>{const rendered=propertyText(value);return rendered?`${notionPlainText(name)}: ${rendered}`:null;}).filter((v):v is string=>Boolean(v)).slice(0,40);}
function schemaProperties(resource:NotionObject):string[]{const props=resource.properties&&typeof resource.properties==="object"?resource.properties as Record<string,unknown>:{};return Object.entries(props).slice(0,50).map(([name,value])=>{const type=value&&typeof value==="object"&&typeof(value as Record<string,unknown>).type==="string"?String((value as Record<string,unknown>).type):"property";return `${notionPlainText(name)} (${notionPlainText(type.replaceAll("_"," "))})`;});}
async function loadResource(userId:string,ref:NotionRef,deps:NotionConversationDeps):Promise<NotionObject>{if(ref.type==="data_source")return(deps.dataSource??notionOps.dataSource)(userId,ref.id);if(ref.type==="database")return(deps.database??notionOps.database)(userId,ref.id);return(deps.page??notionOps.page)(userId,ref.id);}

export async function handleNotionConversation(userId:string,text:string|undefined,deps:NotionConversationDeps={}):Promise<{handled:boolean;reply?:string}>{if(!shouldConsiderNotion(text,deps.arbitrated))return{handled:false};try{const now=deps.now??new Date(),timezone=await(deps.getTimezone??getUserTimezone)(userId),intent=await(deps.extract??extractNotionIntent)({text:text??"",timezone,now:now.toISOString(),context:deps.arbitrated,generate:deps.generate});if(!intent||intent.provider!=="notion"||intent.mode==="not_notion")return{handled:false};const limitation=notionLimitation(intent);if(limitation)return{handled:true,reply:limitation};if(intent.eraseAll)return{handled:true,reply:"I won’t erase every child block through an ordinary edit because Notion’s API cannot restore that content. Remove specific blocks instead."};if(intent.mode==="upload")return{handled:true,reply:"Hula can manage Notion file-upload sessions, but this iMessage transport doesn’t yet provide a trusted binary attachment stream to the backend, so I can’t safely upload that file."};if(intent.mode==="delete"&&intent.entity!=="comment")return{handled:true,reply:"Notion’s public API does not support permanent page deletion. I can archive the page to trash after confirmation instead."};
  if(intent.mode==="search"||intent.mode==="list"){const filter=intent.entity==="page"?{property:"object",value:"page"}:intent.entity==="data_source"?{property:"object",value:"data_source"}:undefined,results=await(deps.search??notionOps.search)(userId,{...(intent.query?{query:intent.query}:{}),...(filter?{filter}:{}),sort:{direction:"descending",timestamp:"last_edited_time"},page_size:intent.count??10});const shown=results.slice(0,intent.count??10);if(!shown.length)return{handled:true,reply:"I couldn’t find any accessible Notion pages or data sources matching that request."};await(deps.recordSelection??recordNotionSelection)(userId,shown);const nouns=[...new Set(shown.map(objectType))],noun=nouns.length===1?`${nouns[0]}${shown.length===1?"":"s"}`:"resources";return{handled:true,reply:`Here ${shown.length===1?"is":"are"} ${shown.length} Notion ${noun}:\n${shown.map((o,i)=>titleLine(o,i+1)).join("\n")}`};}
  if(intent.mode==="users"){const people=await(deps.users??notionOps.users)(userId),shown=people.slice(0,intent.count??10);return{handled:true,reply:shown.length?`Here ${shown.length===1?"is":"are"} ${shown.length} accessible Notion user${shown.length===1?"":"s"}:\n${shown.map((u,i)=>`${i+1}. ${notionPlainText(String(u.name??"Unnamed user"))}`).join("\n")}`:"I couldn’t find any accessible Notion users."};}
  const target=intent.mode==="create"?{ref:null,object:null}:await resolveTarget(userId,intent,deps);if(target.error)return{handled:true,reply:target.error};if((intent.mode==="details"||intent.mode==="summarize"||intent.mode==="comments"||intent.mode==="query")&&!target.ref)return{handled:true,reply:"Which Notion page or data source do you mean?"};
  if(intent.mode==="query"){
    let queryRef=target.ref!;
    if(queryRef.type!=="data_source"){
      const resource=target.resource??(target.object?{ref:{id:queryRef.id,type:queryRef.type as "page"|"database"|"data_source",title:queryRef.title},object:target.object}:null);
      if(!resource)return{handled:true,reply:"I can’t verify which data source belongs to that Notion resource. Name the database or data source explicitly."};
      const queryable=await(deps.resolveQueryable??resolveQueryableDataSource)(userId,resource,resolverDeps(deps));
      if(queryable.kind!=="resolved"){
        if(queryable.kind==="ambiguous")return{handled:true,reply:`That Notion resource contains several data sources: ${queryable.candidates.map(candidate=>`“${notionPlainText(candidate.ref.title)}”`).join(", ")}. Which one should I query?`};
        if(resource.ref.type==="page"){
          const blocks=await(deps.children??notionOps.children)(userId,resource.ref.id),childPages=blocks.filter(block=>block.type==="child_page"&&typeof block.id==="string").slice(0,intent.count??10).map(block=>{const child=block.child_page&&typeof block.child_page==="object"?block.child_page as Record<string,unknown>:{};return{object:"page",id:block.id,title:typeof child.title==="string"?child.title:"Untitled",parent:{type:"page_id",page_id:resource.ref.id}} as NotionObject;});
          if(childPages.length){await(deps.recordSelection??recordNotionSelection)(userId,childPages);return{handled:true,reply:`${childPages.length} Notion child page${childPages.length===1?"":"s"} in “${resource.ref.title}”:\n${childPages.map((page,index)=>`${index+1}. ${notionTitle(page)}`).join("\n")}`};}
        }
        return{handled:true,reply:`“${resource.ref.title}” doesn’t contain an accessible data source or direct child pages I can list.`};
      }
      queryRef=queryable.resource.ref;
    }
    const rows=await(deps.query??notionOps.query)(userId,queryRef.id,{...(intent.filter?{filter:intent.filter}:{}),...(intent.sorts?{sorts:intent.sorts}:{}),page_size:intent.count??10});
    const shown=rows.slice(0,intent.count??10);
    if(shown.length)await(deps.recordSelection??recordNotionSelection)(userId,shown);
    return{handled:true,reply:shown.length?`${shown.length} matching Notion record${shown.length===1?"":"s"}:\n${shown.map((o,i)=>`${i+1}. ${notionTitle(o)}${properties(o).length?` — ${properties(o).slice(0,3).join(" · ")}`:""}`).join("\n")}`:"I found no matching records in that Notion data source."};
  }
  if(intent.mode==="comments"){const comments=await(deps.comments??notionOps.comments)(userId,{block_id:target.ref!.id}),shown=comments.slice(0,intent.count??10);if(shown.length)await(deps.recordSelection??recordNotionSelection)(userId,shown);return{handled:true,reply:shown.length?`Here ${shown.length===1?"is":"are"} ${shown.length} Notion comment${shown.length===1?"":"s"}:\n${shown.map((c,i)=>`${i+1}. ${richText(c.rich_text)}${c.created_time?` — ${new Intl.DateTimeFormat("en-GB",{timeZone:timezone??"UTC",dateStyle:"medium"}).format(new Date(String(c.created_time)))}`:""}`).join("\n")}`:"There are no accessible comments on that Notion page or block."};}
  if(intent.mode==="details"||intent.mode==="summarize"){const resource=target.object??await loadResource(userId,target.ref!,deps);await(deps.recordEntity??recordNotionEntity)(userId,resource);if(target.ref!.type==="data_source"||target.ref!.type==="database"){const schema=schemaProperties(resource);return{handled:true,reply:[`${target.ref!.type==="data_source"?"Data source":"Database"}: ${notionTitle(resource)}`,schema.length?`Properties:\n${schema.join("\n")}`:"Properties: No accessible schema properties."].join("\n")};}const props=properties(resource),blocks=await recursiveBlocks(userId,target.ref!.id,deps),content=notionPlainText(blocks.join("\n\n"),intent.mode==="summarize"?1800:3000),noun=pageKind(resource);return{handled:true,reply:intent.mode==="summarize"?content?`Summary of ${notionTitle(resource)}: ${content}`:`${notionTitle(resource)} has no readable ${noun} content.`:[`${noun[0]!.toUpperCase()+noun.slice(1)}: ${notionTitle(resource)}`,...props,content?`Content: ${content}`:"Content: No readable blocks."].join("\n")};}
  if(intent.mode==="create"){if(!intent.title||!intent.parent)return{handled:true,reply:"Tell me the new page title and the exact parent page or data source."};const parentIntent={...intent,target:intent.parent,position:null} as NotionIntent,parent=await resolveTarget(userId,parentIntent,deps);if(parent.error||!parent.ref)return{handled:true,reply:parent.error??"I couldn’t resolve the Notion parent."};const parentBody=parent.ref.type==="data_source"?{type:"data_source_id",data_source_id:parent.ref.id}:{type:"page_id",page_id:parent.ref.id};const prop=parent.ref.type==="data_source"?{Name:{title:[{text:{content:notionPlainText(intent.title,500)}}]}}:{title:{title:[{text:{content:notionPlainText(intent.title,500)}}]}};const created=await(deps.createPage??notionOps.createPage)(userId,{parent:parentBody,properties:prop,...(intent.content?{children:[textBlock("paragraph",intent.content)]}:{})});await(deps.recordEntity??recordNotionEntity)(userId,created);return{handled:true,reply:`Created the Notion ${parent.ref.type==="data_source"?"record":"page"} “${notionTitle(created)}”.`};}
  if(intent.mode==="update"&&target.ref?.type==="comment"){if(!intent.content)return{handled:true,reply:"What should the updated comment say?"};const preview=`I’ll replace the Notion comment “${notionPlainText(target.ref.title,160)}” with “${notionPlainText(intent.content,300)}”. This is externally visible. ${CONFIRM_INSTRUCTION}`;await(deps.propose??createActionProposal)(userId,{provider:"notion",actionId:"notion.mutate",riskLevel:"write",confirmationRequired:true,input:{operation:"update_comment",targetId:target.ref.id,targetTitle:target.ref.title,body:{rich_text:[{text:{content:notionPlainText(intent.content,2000)}}]}},previewText:preview});return{handled:true,reply:preview};}
  if(intent.mode==="delete"&&target.ref?.type==="comment"){const preview=`I’ll permanently delete the Notion comment “${notionPlainText(target.ref.title,200)}”. Notion’s API does not provide a restore operation for this deletion. ${CONFIRM_INSTRUCTION}`;await(deps.propose??createActionProposal)(userId,{provider:"notion",actionId:"notion.mutate",riskLevel:"write",confirmationRequired:true,input:{operation:"delete_comment",targetId:target.ref.id,targetTitle:target.ref.title,body:{}},previewText:preview});return{handled:true,reply:preview};}
  if(intent.mode==="move"){if(!target.ref||target.ref.type!=="page"||!intent.parent)return{handled:true,reply:"Tell me the exact Notion page and its new parent page or data source."};const destination=await resolveTarget(userId,{...intent,target:intent.parent,position:null,mode:"details"},deps);if(destination.error||!destination.ref)return{handled:true,reply:destination.error??"I couldn’t resolve the new Notion parent."};if(destination.ref.type!=="page"&&destination.ref.type!=="data_source")return{handled:true,reply:"The new parent must be an accessible Notion page or data source."};const parent=destination.ref.type==="page"?{type:"page_id",page_id:destination.ref.id}:{type:"data_source_id",data_source_id:destination.ref.id};const preview=`I’ll move the Notion page “${target.ref.title}” into “${destination.ref.title}”. This changes where collaborators find it. ${CONFIRM_INSTRUCTION}`;await(deps.propose??createActionProposal)(userId,{provider:"notion",actionId:"notion.mutate",riskLevel:"write",confirmationRequired:true,input:{operation:"move_page",targetId:target.ref.id,targetTitle:target.ref.title,body:{parent}},previewText:preview});return{handled:true,reply:preview};}
  if(intent.mode==="update"){if(!target.ref)return{handled:true,reply:"Which Notion page or record should I update?"};if(target.ref.type==="block")return{handled:true,reply:"Tell me the block type and exact replacement content. I won’t guess a block payload that could erase formatting or nested content."};const body:Record<string,unknown>={};if(intent.title)body.properties={title:{title:[{text:{content:notionPlainText(intent.title,500)}}]}};else if(intent.propertyName)body.properties={[intent.propertyName]:intent.propertyValue};else return{handled:true,reply:"What exact Notion property should I change, and what should its new value be?"};if(intent.shared){const change=intent.title?`rename it to “${notionPlainText(intent.title,200)}”`:`change “${notionPlainText(intent.propertyName,120)}”`;const preview=`I’ll ${change} on the shared Notion ${target.ref.type==="page"?"page":"record"} “${target.ref.title}”. This may affect collaborators. ${CONFIRM_INSTRUCTION}`;await(deps.propose??createActionProposal)(userId,{provider:"notion",actionId:"notion.mutate",riskLevel:"write",confirmationRequired:true,input:{operation:"update_page",targetId:target.ref.id,targetTitle:target.ref.title,body},previewText:preview});return{handled:true,reply:preview};}const updated=await(deps.updatePage??notionOps.updatePage)(userId,target.ref.id,body);await(deps.recordEntity??recordNotionEntity)(userId,updated);return{handled:true,reply:`Updated the Notion ${target.ref.type==="page"?"page":"record"} “${notionTitle(updated)}”.`};}
  if(intent.mode==="append"&&!intent.shared){if(!target.ref||!intent.content)return{handled:true,reply:"Tell me the exact Notion page and content to add."};const appended=await(deps.appendBlocks??notionOps.appendBlocks)(userId,target.ref.id,[textBlock("paragraph",intent.content)]);if(!appended||typeof appended!=="object")throw new NotionError("malformed_response");return{handled:true,reply:`Added the paragraph to “${target.ref.title}”.`};}
  if(["archive","restore","comment","schema","append"].includes(intent.mode)){if(!target.ref)return{handled:true,reply:"Which exact Notion target do you mean?"};if(intent.mode==="comment"&&!intent.content)return{handled:true,reply:"What comment should I post?"};const operation=intent.mode==="archive"?(target.ref.type==="block"?"archive_block":"archive_page"):intent.mode==="restore"?"restore_page":intent.mode;const commentTarget=target.ref.type==="comment"&&target.ref.discussionId?{discussion_id:target.ref.discussionId}:target.ref.type==="block"?{parent:{block_id:target.ref.id}}:{parent:{page_id:target.ref.id}};const body=intent.mode==="comment"?{...commentTarget,rich_text:[{text:{content:notionPlainText(intent.content!,2000)}}]}:intent.mode==="append"?{children:[textBlock("paragraph",intent.content??"")]}:intent.mode==="schema"?(intent.propertyName?{properties:{[intent.propertyName]:intent.propertyValue}}:{}):{};const reversible=intent.mode==="archive"||intent.mode==="restore";const preview=intent.mode==="comment"?`I’ll post this comment on “${target.ref.title}”: “${notionPlainText(intent.content!,300)}”. This is externally visible.`:intent.mode==="archive"?`I’ll archive the Notion ${target.ref.type} “${target.ref.title}”. It can be restored through the API where Notion supports restoration.`:intent.mode==="restore"?`I’ll restore the Notion ${target.ref.type} “${target.ref.title}”. This is reversible.`:intent.mode==="schema"?`I’ll change the schema of “${target.ref.title}”. This may affect every collaborator and record.`:`I’ll add content to the shared Notion page “${target.ref.title}”.`;const full=`${preview} ${reversible?"This change is reversible.":"This may affect collaborators."} ${CONFIRM_INSTRUCTION}`;await(deps.propose??createActionProposal)(userId,{provider:"notion",actionId:"notion.mutate",riskLevel:"write",confirmationRequired:true,input:{operation,targetId:target.ref.id,targetTitle:target.ref.title,body},previewText:full});return{handled:true,reply:full};}
  return{handled:true,reply:"That Notion operation isn’t exposed by the current stable public API, so I didn’t make a change."};
 }catch(error){logger.error("notion.conversation failed",{errorCode:error instanceof NotionError?error.code:"unknown"});return{handled:true,reply:errorReply(error)};}}
