import { z } from "zod";
import { generateAnthropicText } from "../../../ai/anthropicClient";

const nullable=z.string().trim().max(2000).nullable().optional();
export const NotionIntentSchema=z.object({provider:z.enum(["notion","google_drive","todoist","asana","calendar","gmail","reminder","memory","unknown"]),mode:z.enum(["search","list","details","summarize","query","comments","users","create","update","append","archive","restore","comment","schema","upload","delete","move","duplicate","unsupported","not_notion"]),entity:z.enum(["page","record","database","data_source","block","comment","user","file","workspace","ai","billing","permission","export","import"]).nullable().optional(),query:nullable,target:nullable,parent:nullable,title:nullable,content:nullable,propertyName:nullable,propertyValue:z.unknown().optional(),filter:z.record(z.unknown()).nullable().optional(),sorts:z.array(z.record(z.unknown())).max(10).nullable().optional(),count:z.number().int().min(1).max(50).nullable().optional(),position:z.number().int().min(1).max(20).nullable().optional(),shared:z.boolean().nullable().optional(),eraseAll:z.boolean().nullable().optional()});
export type NotionIntent=z.infer<typeof NotionIntentSchema>;
export type NotionGenerator=(p:{system:string;messages:{role:"user"|"assistant";content:string}[];maxTokens?:number})=>Promise<string>;
export function shouldConsiderNotion(text:string|undefined,context=false):boolean{const t=(text??"").toLowerCase();if(/\bnotion\b/.test(t))return true;if(context)return true;if(/\b(?:asana|todoist|calendar|email|gmail|inbox|remind|remember|memory)\b/.test(t))return false;const typed=/\b(?:page|data source|database|workspace notes?|blocks?)\b/.test(t);const containedResource=/\b(?:show|list|find|read|summari[sz]e|open|query|tell)\b[\s\S]{0,80}\b(?:notes?|entries|records?|docs?|documents?|content)\b[\s\S]{0,60}\b(?:in|from|inside|under)\s+[\p{L}\p{N}]/iu.test(t);return typed||containedResource;}
export function explicitNotion(text:string|undefined){return /\bnotion\b/i.test(text??"");}
export async function extractNotionIntent(input:{text:string;timezone?:string;now:string;context?:boolean;generate?:NotionGenerator}):Promise<NotionIntent|null>{const system=["Extract one Notion integration intent. Return strict JSON only; never answer or execute.",`Now ${input.now}; IANA timezone ${input.timezone??"UTC"}.`,"Explicit provider language wins. Email is Gmail; events/meetings are Calendar; reminders are reminders; Todoist and Asana stay theirs. The word task alone is unknown unless Notion or a Notion data source context is explicit.",input.context?"Durable arbitration established Notion ownership for pronouns and ordinals.":"No Notion context supplied.","A request for entries, records, notes, or documents inside a named accessible content container is a Notion data-source query when this routing stage supplied compatible Notion context. The container name is target. Preserve arbitrary user-created titles exactly; never interpret a container title as an app name.","Modes: search,list,details,summarize,query,comments,users,create,update,append,archive,restore,comment,schema,upload,delete,move,duplicate,unsupported,not_notion.","Entities: page,record,database,data_source,block,comment,user,file,workspace,ai,billing,permission,export,import.","For filters and sorts, preserve a structured Notion data-source query. Never invent IDs, names, people, dates or property values. Relative dates are resolved in the supplied timezone; date-only remains YYYY-MM-DD. Delete means archive/trash unless permanent deletion is unmistakably requested, which is unsupported. eraseAll is true only for an explicit request to erase every child block.",`Shape: ${JSON.stringify({provider:"notion",mode:"search",entity:"page",query:null,target:null,parent:null,title:null,content:null,propertyName:null,propertyValue:null,filter:null,sorts:null,count:null,position:null,shared:null,eraseAll:null})}`].join("\n");try{const raw=await(input.generate??generateAnthropicText)({system,messages:[{role:"user",content:input.text}],maxTokens:700}),a=raw.indexOf("{"),b=raw.lastIndexOf("}");if(a<0||b<=a)return null;const parsed=NotionIntentSchema.safeParse(JSON.parse(raw.slice(a,b+1)));return parsed.success?parsed.data:null;}catch{return null;}}
export function notionLimitation(intent:NotionIntent):string|null{if(intent.entity==="ai")return"Notion AI isn’t exposed through Notion’s public API, so Hula can’t run or administer it.";if(intent.entity==="billing")return"Notion’s public API doesn’t expose billing or plan management.";if(intent.entity==="permission")return"Notion’s public API doesn’t let Hula change workspace sharing or permissions.";if(intent.entity==="export"||intent.entity==="import")return"Notion’s stable public API doesn’t expose workspace import or export operations.";if(intent.mode==="duplicate")return"Notion’s stable public API doesn’t expose a general page-duplication endpoint.";return null;}
