import assert from "node:assert/strict";
import { explicitEntityKinds, resolveFollowupOwner } from "../src/actions/entityContextArbiter";
import { handleEntityFollowup } from "../src/routes/entityFollowup";
import { routeInboundText } from "../src/routes/inboundRouting";
import type { ActionProposalView } from "../src/actions/proposals";

const row=(actionId:string,createdAt:string):ActionProposalView=>({id:`${actionId}-${createdAt}`,provider:actionId.startsWith("asana")?"asana":"todoist",actionId,status:"proposed",riskLevel:"read",confirmationRequired:false,previewText:"context",input:{kind:"context"},expiresAt:"2099-01-01T00:00:00.000Z",confirmedAt:null,rejectedAt:null,executedAt:null,createdAt});
async function main(){
  assert.deepEqual(explicitEntityKinds("complete that Asana task"),["asana_task"]);
  assert.deepEqual(explicitEntityKinds("complete that Todoist task"),["todoist_task"]);
  const list=async(_u:string,a:string)=>a.startsWith("asana")?[row(a,"2026-07-15T10:00:02.000Z")]:a.startsWith("todoist")?[row(a,"2026-07-15T10:00:01.000Z")]:[];
  for(const phrase of ["complete it","reopen it","delete it","the second one","move it","change its due date to Friday at 4 PM"]){const owner=await resolveFollowupOwner("u",phrase,{listRecent:list,now:new Date("2026-07-15T10:05:00Z")});assert.equal(owner.kind,"owner",phrase);if(owner.kind==="owner")assert.equal(owner.owner,"asana_task",phrase);}
  const todoList=async(_u:string,a:string)=>a.startsWith("todoist")?[row(a,"2026-07-15T10:00:03.000Z")]:a.startsWith("asana")?[row(a,"2026-07-15T10:00:02.000Z")]:[];const todoOwner=await resolveFollowupOwner("u","complete it",{listRecent:todoList,now:new Date("2026-07-15T10:05:00Z")});assert.equal(todoOwner.kind,"owner");if(todoOwner.kind==="owner")assert.equal(todoOwner.owner,"todoist_task");
  const same=async(_u:string,a:string)=>a.startsWith("asana")||a.startsWith("todoist")?[row(a,"2026-07-15T10:00:00.000Z")]:[];const conflict=await resolveFollowupOwner("u","delete it",{listRecent:same,now:new Date("2026-07-15T10:05:00Z")});assert.equal(conflict.kind,"conflict");let asanaWrites=0,todoWrites=0;const guarded=await handleEntityFollowup("u","delete it",{resolveOwner:async()=>conflict,asanaWrite:async()=>{asanaWrites++;return{handled:true,reply:"bad"}},todoistWrite:async()=>{todoWrites++;return{handled:true,reply:"bad"}}});assert.equal(guarded.handled,true);assert.match(guarded.reply??"",/Asana task.*Todoist task|Todoist task.*Asana task/);assert.equal(asanaWrites+todoWrites,0);
  let readCalls=0,writeCalls=0;const details=await handleEntityFollowup("u","Tell me more about the second one",{resolveOwner:async()=>({kind:"owner",owner:"asana_task",reason:"context"}),asanaRead:async()=>{readCalls++;return{handled:true,reply:"Task: Second"}},asanaWrite:async()=>{writeCalls++;return{handled:true,reply:"wrong"}}});assert.equal(details.reply,"Task: Second");assert.equal(readCalls,1);assert.equal(writeCalls,0);
  const completion=await handleEntityFollowup("u","complete it",{resolveOwner:async()=>({kind:"owner",owner:"asana_task",reason:"context"}),asanaRead:async()=>({handled:false}),asanaWrite:async()=>{writeCalls++;return{handled:true,reply:"complete proposal"}}});assert.equal(completion.reply,"complete proposal");assert.equal(writeCalls,1);
  const decline=async()=>({handled:false});const base={transportKeyword:decline,memory:decline,reminder:decline,confirmation:decline,entityFollowup:decline,gmailClarify:decline,gmailDraftFollowup:decline,gmailDraftLifecycle:decline,gmailCommand:decline,calendarUndo:decline,calendarWrite:decline,gmailWrite:decline,actionIntent:decline,calendarAvailability:decline,calendar:decline,calendarRead:decline,gmailReadOne:decline,gmailSummary:decline,gmailSearch:decline,gmailQuestion:decline,todoistUndo:decline,todoistWrite:decline,todoistRead:decline,asanaWrite:decline,asanaRead:decline,pendingReprompt:async()=>({handled:false})};
  let calendar=0,gmail=0;const reminder=await routeInboundText("u","remind me to complete it",{...base,reminder:async()=>({handled:true,reply:"reminder"}),calendarWrite:async()=>{calendar++;return{handled:true,reply:"calendar"}},gmailCommand:async()=>{gmail++;return{handled:true,reply:"gmail"}}});assert.equal(reminder?.source,"reminder");assert.equal(calendar+gmail,0);
  const memory=await routeInboundText("u","remember that Asana is for work",{...base,memory:async()=>({handled:true,reply:"memory"}),reminder:async()=>({handled:false})});assert.equal(memory?.source,"memory");
  const gmailResult=await routeInboundText("u","reply to that email",{...base,memory:async()=>({handled:false}),reminder:async()=>({handled:false}),gmailCommand:async()=>({handled:true,reply:"gmail"})});assert.equal(gmailResult?.source,"gmailCommand");
  const calendarResult=await routeInboundText("u","move that calendar event",{...base,memory:async()=>({handled:false}),reminder:async()=>({handled:false}),gmailCommand:async()=>({handled:false}),calendarUndo:async()=>({handled:false}),calendarWrite:async()=>({handled:true,reply:"calendar"})});assert.equal(calendarResult?.source,"calendarWrite");
  console.log("asana routing tests passed");
}
void main();
