import assert from "node:assert/strict";
import { handleActionConfirmation } from "../src/actions/confirmations";
import type { ActionProposalView } from "../src/actions/proposals";
import { executeAction } from "../src/actions/executor";

const proposal:ActionProposalView={id:"p1",provider:"asana",actionId:"asana.task.delete",status:"proposed",riskLevel:"write",confirmationRequired:true,previewText:"Delete Task permanently?",input:{taskIds:["1"],titles:["Task"]},expiresAt:"2099-01-01T00:00:00.000Z",confirmedAt:null,rejectedAt:null,executedAt:null,createdAt:"2026-07-15T00:00:00.000Z"};
async function main(){
  let active:ActionProposalView|null=proposal,writes=0,finalized=0;
  const deps={getActiveProposal:async()=>active,confirmProposal:async()=>{if(!active)return null;const value=active;active=null;return value;},rejectProposal:async()=>{active=null;return true;},finalizeProposal:async()=>{finalized++;},executeAction:async()=>{writes++;return{ok:true,status:"succeeded" as const,actionId:"asana.task.delete",provider:"asana",userMessage:"Deleted."}}};
  const no=await handleActionConfirmation("u","No",deps as any);assert.equal(no.outcome,"cancelled");assert.equal(writes,0);
  active=proposal;const yes=await handleActionConfirmation("u","Yes",deps as any);assert.equal(yes.outcome,"confirmed");assert.equal(writes,1);assert.equal(finalized,1);const repeated=await handleActionConfirmation("u","Yes",deps as any);assert.equal(repeated.handled,false);assert.equal(writes,1);
  let deletes=0;const unknown=await executeAction("u","asana.task.delete",{input:{taskIds:["1"],titles:["Task"]},userConfirmed:true},{buildContext:async()=>({connectedProviders:["asana"],grantedScopesByProvider:{asana:["tasks:delete"]},capabilitiesByProvider:{asana:["tasks.delete"]},userConfirmed:true}),record:async()=>"e",deleteAsanaResource:async()=>{deletes++;throw Object.assign(new Error("timeout"),{name:"TimeoutError"})},recordAsanaEntity:async()=>({id:"never"})});assert.equal(unknown.ok,false);assert.equal(deletes,1);assert.doesNotMatch(unknown.userMessage,/deleted/i);
  let calls=0;const partial=await executeAction("u","asana.task.update",{input:{taskIds:["1","2"],fields:{completed:true}},userConfirmed:true},{buildContext:async()=>({connectedProviders:["asana"],grantedScopesByProvider:{asana:["tasks:write"]},capabilitiesByProvider:{asana:["tasks.write"]},userConfirmed:true}),record:async()=>"e2",updateAsanaTask:async(_u,id)=>{calls++;if(id==="2")throw new Error("fail");return{gid:id,resourceType:"task",name:id,permalinkUrl:null,completed:true}},getAsanaResource:async(_u,_k,id)=>({gid:id,name:id,resource_type:"task",completed:true}),recordAsanaEntity:async()=>({id:"ctx"})});assert.equal(calls,2);assert.equal(partial.ok,false);assert.match(partial.userMessage,/1 of 2/);
  let remembered=0;const follower=await executeAction("u","asana.task.relationship",{input:{taskIds:["1"],relationshipAction:"addFollowers",relationshipInput:{followers:["7"]}},userConfirmed:true},{buildContext:async()=>({connectedProviders:["asana"],grantedScopesByProvider:{asana:["tasks:write"]},capabilitiesByProvider:{asana:["tasks.write"]},userConfirmed:true}),record:async()=>"relationship",mutateAsanaRelationship:async()=>({gid:"1",resourceType:"task",name:"Task",permalinkUrl:null,completed:false}),getAsanaResource:async()=>({gid:"1",name:"Task",resource_type:"task",followers:[{gid:"7",name:"Ayub"}]}),recordAsanaEntity:async()=>{remembered++;return{id:"relationship-context"}}});assert.equal(follower.ok,true);assert.equal(remembered,1);
  const relationshipMismatch=await executeAction("u","asana.task.relationship",{input:{taskIds:["1"],relationshipAction:"addFollowers",relationshipInput:{followers:["7"]}},userConfirmed:true},{buildContext:async()=>({connectedProviders:["asana"],grantedScopesByProvider:{asana:["tasks:write"]},capabilitiesByProvider:{asana:["tasks.write"]},userConfirmed:true}),record:async()=>"relationship-failed",mutateAsanaRelationship:async()=>({gid:"1",resourceType:"task",name:"Task",permalinkUrl:null,completed:false}),getAsanaResource:async()=>({gid:"1",name:"Task",resource_type:"task",followers:[]}),recordAsanaEntity:async()=>{throw new Error("must not remember")}});assert.equal(relationshipMismatch.ok,false);assert.equal(relationshipMismatch.receipt,undefined);
  console.log("asana safety tests passed");
}
void main();
