import assert from "node:assert/strict";

import { executeAction } from "../src/actions/executor";
import type { ActionProposalView } from "../src/actions/proposals";
import { handleAsanaWrite } from "../src/integrations/providers/asana/asanaActions";
import { AsanaError } from "../src/integrations/providers/asana/client";
import { isAsanaReferencePhrase, recordAsanaEntity, recordAsanaSelection, resolveAsanaReference } from "../src/integrations/providers/asana/asanaContext";
import { handleAsanaRead } from "../src/integrations/providers/asana/asanaReads";
import { buildAsanaSectionMoveRequest } from "../src/integrations/providers/asana/operations";
import { resolveAsanaTaskTitle } from "../src/integrations/providers/asana/asanaTaskResolver";
import type { AsanaResource } from "../src/integrations/providers/asana/types";
import { routeInboundText } from "../src/routes/inboundRouting";

const project={gid:"10",name:"Hula test",resource_type:"project"};
const execution={gid:"30",name:"Execution",resource_type:"section"};
const planning={gid:"20",name:"Planning",resource_type:"section"};
const task=(gid:string,name:string,section=planning,extra:Record<string,unknown>={}):AsanaResource=>({gid,name,resource_type:"task",completed:false,due_at:"2026-07-17T16:00:00.000Z",notes:"Created safely through Hula",assignee:{gid:"7",name:"Ayub"},followers:[{gid:"8",name:"Ada"}],custom_fields:[{gid:"9",name:"Priority",display_value:"High"}],memberships:[{project,section}],projects:[project],...extra});

function contextStore(){const rows:ActionProposalView[]=[];return{rows,store:{create:async(_u:string,input:any)=>{const now=new Date();const row={id:String(rows.length+1),provider:input.provider??null,actionId:input.actionId,status:"proposed",riskLevel:input.riskLevel,confirmationRequired:input.confirmationRequired??true,previewText:input.previewText,input:input.input??null,expiresAt:new Date(now.getTime()+(input.ttlMs??600000)).toISOString(),confirmedAt:null,rejectedAt:null,executedAt:null,createdAt:new Date(now.getTime()+rows.length).toISOString()} as ActionProposalView;rows.unshift(row);return{id:row.id};},listRecent:async(_u:string,a:string)=>rows.filter(row=>row.actionId===a)}};}
const decline=async()=>({handled:false});
const routeBase={transportKeyword:decline,memory:decline,reminder:decline,confirmation:decline,entityFollowup:decline,gmailClarify:decline,gmailDraftFollowup:decline,gmailDraftLifecycle:decline,gmailCommand:decline,calendarUndo:decline,todoistUndo:decline,todoistWrite:decline,todoistRead:decline,calendarWrite:decline,gmailWrite:decline,actionIntent:decline,calendarAvailability:decline,calendar:decline,calendarRead:decline,gmailReadOne:decline,gmailSummary:decline,gmailSearch:decline,gmailQuestion:decline,pendingReprompt:decline};
const workspaceAndProjects=async(_u:string,kind:string)=>kind==="workspaces"?[{gid:"1",name:"Acme",resource_type:"workspace"}]:[project];

async function main(){
  const named=task("100","Hula Asana Write Test");const otherAssigned=[task("101","Assigned one"),task("102","Assigned two")];const executionMarker=task("103","Existing execution work",execution);const otherProject={gid:"11",name:"Other",resource_type:"project"};const otherExecution=task("109","Other project execution",{gid:"40",name:"Execution",resource_type:"section"},{memberships:[{project:otherProject,section:{gid:"40",name:"Execution",resource_type:"section"}}],projects:[otherProject]});let all=[named,...otherAssigned,executionMarker,otherExecution];
  const listTasks=async(_u:string,params:any)=>params.project?all.filter(item=>(item.memberships as any[])[0]?.project?.gid===params.project):params.section?all.filter(item=>(item.memberships as any[])[0]?.section?.gid===params.section):otherAssigned;
  const searchWorkspace=async()=>all;

  const lookupCtx=contextStore();const readDeps={now:new Date("2026-07-16T12:00:00.000Z"),getTimezone:async()=>"Europe/London",extract:async()=>({provider:"asana" as const,mode:"read" as const,entity:"task" as const,targetPhrase:"Hula Asana Write Test"}),listResources:workspaceAndProjects as any,listTasks:listTasks as any,searchWorkspace:searchWorkspace as any,getResource:async(_u:string,_kind:string,id:string)=>{assert.equal(id,"100");return named},listChildren:async()=>[],recordSelection:async()=>{throw new Error("named details must not store an assigned-task list")},recordEntity:async(u:string,item:any)=>recordAsanaEntity(u,item,"details",lookupCtx.store)};
  const routed=await routeInboundText("u","Show me the details for Hula Asana Write Test",{...routeBase,asanaWrite:async()=>({handled:false}),asanaRead:(u,t)=>handleAsanaRead(u,t,readDeps as any)});assert.equal(routed?.source,"asanaRead");assert.match(routed?.reply??"",/^Task: Hula Asana Write Test/);assert.doesNotMatch(routed?.reply??"",/Assigned one|Assigned two/);
  assert.equal((await resolveAsanaReference("u","it",null,null,lookupCtx.store)).item?.id,"100");
  for(const phrase of ["it","its","that","that task","this","this task","the task","the one","the one you just showed","the one you just created","the one you just updated","the one you just assigned","the one you just moved"])assert.equal(isAsanaReferencePhrase(phrase),true,phrase);
  assert.equal((await resolveAsanaReference("u","Change its due date",null,"its",lookupCtx.store)).item?.id,"100");
  let dueInput:any=null,referenceCalls=0;const dueChange=await handleAsanaWrite("u","Change its due date to Friday at 4 PM",{arbitrated:true,now:new Date("2026-07-16T12:00:00.000Z"),getTimezone:async()=>"Europe/London",extract:async()=>({provider:"asana",mode:"update",entity:"task",targetPhrase:"its",dueDate:"2026-07-17",dueTime:"16:00"}),resolveReference:async()=>{referenceCalls++;return resolveAsanaReference("u","Change its due date to Friday at 4 PM",null,"its",lookupCtx.store);},getResource:async()=>named,execute:async(_u,action,options)=>{dueInput=options!.input;return{ok:true,status:"succeeded",actionId:action,provider:"asana",userMessage:"Updated that Asana task.",executionId:"due",receipt:{asanaResourceIds:["100"]}}},recordEntity:async()=>({id:"due-context"})});assert.equal(referenceCalls,1);assert.equal(dueChange.reply,"Updated that Asana task.");assert.deepEqual(dueInput.taskIds,["100"]);assert.equal(dueInput.fields.due_at,"2026-07-17T15:00:00.000Z");

  const resolverDeps={listResources:workspaceAndProjects as any,listTasks:listTasks as any,searchWorkspace:searchWorkspace as any};
  assert.equal((await resolveAsanaTaskTitle("u","hUlA aSaNa WrItE tEsT",resolverDeps)).kind,"resolved");
  assert.equal((await resolveAsanaTaskTitle("u","Asana Write",resolverDeps)).kind,"resolved");
  all=[...all,task("104","Hula Asana Write Test copy")];assert.equal((await resolveAsanaTaskTitle("u","Hula Asana Write",resolverDeps)).kind,"ambiguous");all=all.filter(item=>item.gid!=="104");assert.equal((await resolveAsanaTaskTitle("u","Missing title",resolverDeps)).kind,"not_found");

  const ambiguousRead=await handleAsanaRead("u","details for Hula Asana Write",{...readDeps,extract:async()=>({provider:"asana",mode:"read",entity:"task",targetPhrase:"Hula Asana Write"}),searchWorkspace:async()=>[named,task("104","Hula Asana Write copy")] as any});assert.match(ambiguousRead.reply??"",/multiple Asana tasks/);
  const missingRead=await handleAsanaRead("u","details for Missing title in Asana",{...readDeps,extract:async()=>({provider:"asana",mode:"read",entity:"task",targetPhrase:"Missing title"}),searchWorkspace:async()=>[] as any,listTasks:async()=>[] as any});assert.match(missingRead.reply??"",/couldn’t find an accessible Asana task/);

  assert.deepEqual(buildAsanaSectionMoveRequest("100","30"),{path:"/sections/30/addTask",data:{task:"100"}});
  let relationshipCalls=0,remembered=0;const original={due_at:named.due_at,notes:named.notes,assignee:named.assignee,followers:named.followers,custom_fields:named.custom_fields,projects:named.projects};
  const runMove=async(input:Record<string,unknown>)=>executeAction("u","asana.task.relationship",{input,userConfirmed:true},{buildContext:async()=>({connectedProviders:["asana"],grantedScopesByProvider:{asana:["tasks:read","tasks:write"]},capabilitiesByProvider:{asana:["tasks.read","tasks.write"]},userConfirmed:true}),record:async()=>"move-execution",getAsanaResource:async()=>named,listAsanaTasks:async(_u,params)=>params?.section==="30"&&relationshipCalls>0?[named]:all,mutateAsanaRelationship:async(_u,id,action,payload)=>{relationshipCalls++;assert.equal(id,"100");assert.equal(action,"moveToSection");assert.deepEqual(payload,{section:"30",project:"10"});named.memberships=[{project,section:execution}];return{taskGid:"100",operation:"moveToSection",sectionGid:"30",accepted:true}},recordAsanaEntity:async()=>{remembered++;return{id:"moved"}}});
  const moveInput={taskIds:["100"],titles:["Hula Asana Write Test"],relationshipAction:"moveToSection",relationshipInput:{section:"30",project:"10",sectionName:"Execution"}};const moved=await runMove(moveInput);assert.equal(moved.ok,true);assert.match(moved.userMessage,/Moved.*Execution/);assert.equal(relationshipCalls,1);assert.equal(remembered,1);assert.deepEqual({due_at:named.due_at,notes:named.notes,assignee:named.assignee,followers:named.followers,custom_fields:named.custom_fields,projects:named.projects},original);
  const repeatedMove=await runMove(moveInput);assert.equal(repeatedMove.ok,true);assert.match(repeatedMove.userMessage,/already in Execution/);assert.equal(relationshipCalls,1);

  named.memberships=[{project,section:planning}];let executedInput:any=null;const moveHandler=await handleAsanaWrite("u","Move Hula Asana Write Test to the Execution section",{getTimezone:async()=>"Europe/London",extract:async()=>({provider:"asana",mode:"move",entity:"task",targetPhrase:"Hula Asana Write Test",sectionName:"Execution"}),listResources:workspaceAndProjects as any,listTasks:listTasks as any,searchWorkspace:searchWorkspace as any,getResource:async()=>named,execute:async(_u,action,options)=>{assert.equal(action,"asana.task.relationship");executedInput=options?.input;return{ok:true,status:"succeeded",actionId:action,provider:"asana",userMessage:"Moved safely",executionId:"e",receipt:{asanaResourceIds:["100"]}}},recordEntity:async()=>({id:"post"})});assert.equal(moveHandler.reply,"Moved safely");assert.equal(executedInput.relationshipAction,"moveToSection");assert.deepEqual(executedInput.relationshipInput,{section:"30",project:"10",sectionName:"Execution"});

  let writes=0;const missingSection=await handleAsanaWrite("u","Move Hula Asana Write Test to Missing section",{getTimezone:async()=>"UTC",extract:async()=>({provider:"asana",mode:"move",entity:"task",targetPhrase:"Hula Asana Write Test",sectionName:"Missing"}),listResources:workspaceAndProjects as any,listTasks:listTasks as any,searchWorkspace:searchWorkspace as any,getResource:async()=>named,execute:async()=>{writes++;throw new Error("must not write")}});assert.match(missingSection.reply??"",/couldn’t find an “Missing” section/);assert.equal(writes,0);
  all=[...all,task("105","Duplicate section A",{gid:"31",name:"Execution",resource_type:"section"}),task("106","Duplicate section B",{gid:"32",name:"Execution",resource_type:"section"})];const duplicateSection=await handleAsanaWrite("u","Move Hula Asana Write Test to Execution section",{getTimezone:async()=>"UTC",extract:async()=>({provider:"asana",mode:"move",entity:"task",targetPhrase:"Hula Asana Write Test",sectionName:"Execution"}),listResources:workspaceAndProjects as any,listTasks:listTasks as any,searchWorkspace:searchWorkspace as any,getResource:async()=>named,execute:async()=>{writes++;throw new Error("must not write")}});assert.match(duplicateSection.reply??"",/duplicate “Execution” sections/);assert.equal(writes,0);all=all.filter(item=>!["105","106"].includes(item.gid));

  for(const [reason,status,pattern] of [["invalid_request",400,/invalid/],["auth_failed",401,/reconnected/],["forbidden",403,/permission/],["not_found",404,/no longer accessible/],["rate_limited",429,/rate-limiting/],["provider_unavailable",503,/couldn’t complete/]] as const){const failed=await executeAction("u","asana.task.relationship",{input:moveInput,userConfirmed:true},{buildContext:async()=>({connectedProviders:["asana"],grantedScopesByProvider:{asana:["tasks:write"]},capabilitiesByProvider:{asana:["tasks.write"]},userConfirmed:true}),record:async()=>"failure",getAsanaResource:async()=>({...named,memberships:[{project,section:planning}]}),listAsanaTasks:async()=>[],mutateAsanaRelationship:async()=>{throw new AsanaError(reason,status)},recordAsanaEntity:async()=>{throw new Error("must not remember")}});assert.equal(failed.ok,false,reason);assert.match(failed.userMessage,pattern,reason);}
  const malformed=await executeAction("u","asana.task.relationship",{input:moveInput,userConfirmed:true},{buildContext:async()=>({connectedProviders:["asana"],grantedScopesByProvider:{asana:["tasks:write"]},capabilitiesByProvider:{asana:["tasks.write"]},userConfirmed:true}),record:async()=>"malformed",getAsanaResource:async()=>({...named,memberships:[{project,section:planning}]}),listAsanaTasks:async()=>[],mutateAsanaRelationship:async()=>({gid:"100",resourceType:"task",name:null,permalinkUrl:null,completed:null}),recordAsanaEntity:async()=>{throw new Error("must not remember")}});assert.equal(malformed.ok,false);assert.match(malformed.userMessage,/invalid move receipt/);

  const creationTasks:AsanaResource[]=[];let creates=0,captured:any=null;const creationDeps={now:new Date("2026-07-16T09:00:00.000Z"),getTimezone:async()=>"Europe/London",extract:async()=>({provider:"asana" as const,mode:"create" as const,entity:"task" as const,name:"Hula Asana Write Test",projectName:"Hula test",dueDate:"2026-07-17",dueTime:"17:00",notes:"Created safely through Hula"}),listResources:workspaceAndProjects as any,listTasks:async()=>creationTasks,execute:async(_u:string,action:string,options:any)=>{creates++;captured=options.input;const created=task("200",captured.name,planning,{due_at:captured.due_at,notes:captured.notes});creationTasks.push(created);return{ok:true,status:"succeeded" as const,actionId:action,provider:"asana",userMessage:"Created once",executionId:"create",receipt:{asanaResourceIds:["200"]}}},getResource:async()=>creationTasks[0]!,recordEntity:async()=>({id:"created"})};const created=await handleAsanaWrite("u","Create an Asana task called Hula Asana Write Test in my Hula test project, due tomorrow at 5 PM, with the description Created safely through Hula",creationDeps);assert.equal(created.reply,"Created once");assert.equal(creates,1);assert.equal(captured.name,"Hula Asana Write Test");assert.deepEqual(captured.projects,["10"]);assert.equal(captured.due_at,"2026-07-17T16:00:00.000Z");assert.equal(captured.notes,"Created safely through Hula");const duplicateDelivery=await handleAsanaWrite("u","Create an Asana task called Hula Asana Write Test in my Hula test project, due tomorrow at 5 PM, with the description Created safely through Hula",creationDeps);assert.match(duplicateDelivery.reply??"",/already exists.*didn’t create a duplicate/);assert.equal(creates,1);
  let providerCreatePayload:any=null;const verifiedCreate=await executeAction("u","asana.task.create",{input:captured,userConfirmed:true},{buildContext:async()=>({connectedProviders:["asana"],grantedScopesByProvider:{asana:["tasks:read","tasks:write"]},capabilitiesByProvider:{asana:["tasks.read","tasks.write"]},userConfirmed:true}),record:async()=>"verified-create",createAsanaTask:async(_u,input)=>{providerCreatePayload=input;return{gid:"200",resourceType:"task",name:"Hula Asana Write Test",permalinkUrl:null,completed:false}},getAsanaResource:async()=>creationTasks[0]!,recordAsanaEntity:async()=>({id:"verified-context"})});assert.equal(verifiedCreate.ok,true);assert.deepEqual(providerCreatePayload,captured);

  const ctx=contextStore();await recordAsanaSelection("ctx",[named],ctx.store);await recordAsanaEntity("ctx",{id:"100",type:"task",title:"Hula Asana Write Test",completed:false,project:"Hula test",section:"Planning",due:null,permalink:null},"read",ctx.store);const pronounMove=await handleAsanaWrite("ctx","move it to Execution",{arbitrated:true,getTimezone:async()=>"UTC",extract:async()=>({provider:"asana",mode:"move",entity:"task",sectionName:"Execution"}),resolveReference:async(u,t,p,q)=>resolveAsanaReference(u,t,p,q,ctx.store),listTasks:listTasks as any,getResource:async()=>({...named,memberships:[{project,section:planning}]}),execute:async()=>({ok:true,status:"succeeded",actionId:"asana.task.relationship",provider:"asana",userMessage:"Moved context task",executionId:"context",receipt:{asanaResourceIds:["100"]}}),recordEntity:async()=>({id:"context-post"})});assert.equal(pronounMove.reply,"Moved context task");

  console.log("asana lookup and section move tests passed");
}
void main();
