import assert from "node:assert/strict";
import { executeAction } from "../src/actions/executor";
import { handleAsanaWrite } from "../src/integrations/providers/asana/asanaActions";
import { resolveAsanaPersonFromList } from "../src/integrations/providers/asana/asanaIdentity";
import { handleAsanaRead } from "../src/integrations/providers/asana/asanaReads";
import { capabilitiesFromAsanaScopes } from "../src/integrations/providers/asana/oauth";

const context=(scope:string,capability:string)=>async()=>({connectedProviders:["asana"],grantedScopesByProvider:{asana:[scope]},capabilitiesByProvider:{asana:[capability]},userConfirmed:true});
async function main(){
  assert.deepEqual(capabilitiesFromAsanaScopes(["project_sections:write","goals:delete","time_tracking_entries:delete"]),[]);
  const people=[{gid:"1",name:"Sarah",email:"sarah@example.test"},{gid:"2",name:"Sarah",email:"sarah.two@example.test"}];assert.equal(resolveAsanaPersonFromList(people,"Sarah").kind,"ambiguous");assert.equal(resolveAsanaPersonFromList(people,"sarah@example.test").kind,"resolved");assert.equal(resolveAsanaPersonFromList(people,"Sam").kind,"not_found");
  const children=await handleAsanaRead("u","show comments on that Asana task",{getTimezone:async()=>"UTC",extract:async()=>({provider:"asana",mode:"read",entity:"comment",count:3}),resolveReference:async()=>({item:{id:"t1",type:"task",title:"Task",completed:false,project:null,section:null,due:null,permalink:null},ambiguous:false}),listChildren:async(_u,_p,_id,child)=>{assert.equal(child,"stories");return[{gid:"s1",resource_type:"story",text:"Ready"}]},recordSelection:async()=>({id:"c"}),recordEntity:async()=>({id:"ce"})});assert.match(children.reply??"",/Ready/);
  const attachments=await handleAsanaRead("u","show its attachments",{arbitrated:true,getTimezone:async()=>"UTC",extract:async()=>({provider:"asana",mode:"read",entity:"attachment"}),resolveReference:async()=>({item:{id:"t1",type:"task",title:"Task",completed:false,project:null,section:null,due:null,permalink:null},ambiguous:false}),listChildren:async()=>[{gid:"a1",resource_type:"attachment",name:"spec.pdf",resource_subtype:"asana",host:"asana"}],recordSelection:async()=>({id:"a"}),recordEntity:async()=>({id:"ae"})});assert.match(attachments.reply??"",/attachment:\nspec\.pdf/);assert.match(attachments.reply??"",/content isn’t retrieved/);assert.doesNotMatch(attachments.reply??"",/https?:|gid/i);
  const time=await handleAsanaRead("u","how much time was logged on it",{arbitrated:true,getTimezone:async()=>"UTC",extract:async()=>({provider:"asana",mode:"read",entity:"time_entry"}),resolveReference:async()=>({item:{id:"t1",type:"task",title:"Task",completed:false,project:null,section:null,due:null,permalink:null},ambiguous:false}),listChildren:async()=>[{gid:"e1",resource_type:"time_tracking_entry",name:"Research",duration_minutes:30},{gid:"e2",resource_type:"time_tracking_entry",name:"Review",duration_minutes:45}],recordSelection:async()=>({id:"time"})});assert.match(time.reply??"",/Total logged: 75 minutes/);
  const portfolioProjects=await handleAsanaRead("u","what projects are in my Roadmap portfolio?",{getTimezone:async()=>"UTC",extract:async()=>({provider:"asana",mode:"read",entity:"project",portfolioName:"Roadmap"}),listResources:async(_u,kind)=>kind==="workspaces"?[{gid:"1",name:"Acme"}]:[{gid:"20",name:"Roadmap",resource_type:"portfolio"}],listChildren:async(_u,parent,id,child)=>{assert.equal(parent,"portfolios");assert.equal(id,"20");assert.equal(child,"items");return[{gid:"30",name:"Launch",resource_type:"project"}]},recordSelection:async()=>({id:"portfolio-projects"}),recordEntity:async()=>({id:"portfolio-project"})});assert.match(portfolioProjects.reply??"",/project in Roadmap:\nLaunch/);
  let sectionCalls=0;const sections=await handleAsanaRead("u","show sections in Launch on Asana",{getTimezone:async()=>"UTC",extract:async()=>({provider:"asana",mode:"read",entity:"section",projectName:"Launch"}),listResources:async()=>{sectionCalls++;return[]},listChildren:async()=>{sectionCalls++;return[]},recordSelection:async()=>({id:"s"}),recordEntity:async()=>({id:"se"})});assert.match(sections.reply??"",/do not expose section resources/i);assert.equal(sectionCalls,0);
  for(const [entity,pattern] of [["project_brief",/named OAuth scope/],["export",/admin\/service-account/],["webhook",/isn’t enabled/]] as const){let calls=0;const unsupported=await handleAsanaRead("u",`show Asana ${entity}`,{getTimezone:async()=>"UTC",extract:async()=>({provider:"asana",mode:"read",entity}),listResources:async()=>{calls++;return[]}});assert.match(unsupported.reply??"",pattern);assert.equal(calls,0);}
  for(const [entity,scope,capability,kind] of [["project","projects:write","projects.write","projects"],["portfolio","portfolios:write","portfolios.write","portfolios"]] as const){let creates=0,remembered=0;const result=await executeAction("u",`asana.${entity}.write`,{input:{operation:"create",data:{name:"X"}},userConfirmed:true},{buildContext:context(scope,capability),record:async()=>"e",createAsanaResource:async(_u,k)=>{creates++;assert.equal(k,kind);return{gid:"10",resourceType:k,name:"X",permalinkUrl:null,completed:null}},getAsanaResource:async()=>({gid:"10",name:"X",resource_type:entity}),recordAsanaEntity:async()=>{remembered++;return{id:"resource-context"}}});assert.equal(result.ok,true,entity);assert.equal(creates,1,entity);assert.equal(remembered,1,entity);}
  let deletes=0;const deleted=await executeAction("u","asana.project.delete",{input:{resourceId:"10",title:"Launch"},userConfirmed:true},{buildContext:context("projects:delete","projects.delete"),record:async()=>"d",deleteAsanaResource:async()=>{deletes++;return{deleted:true,gid:"10"}},recordAsanaEntity:async()=>({id:"deleted-context"})});assert.equal(deleted.ok,true);assert.equal(deletes,1);
  let membershipCalls=0;const membership=await executeAction("u","asana.portfolio.membership",{input:{portfolioId:"20",itemId:"30",operation:"addItem"},userConfirmed:true},{buildContext:context("portfolios:write","portfolios.write"),record:async()=>"pm",mutateAsanaPortfolioItem:async(_u,portfolio,operation,item)=>{membershipCalls++;assert.deepEqual({portfolio,operation,item},{portfolio:"20",operation:"addItem",item:"30"});return{portfolioGid:"20",itemGid:"30",operation,accepted:true}},listAsanaChildren:async()=>[{gid:"30",name:"Launch",resource_type:"project"}],getAsanaResource:async()=>({gid:"20",name:"Roadmap",resource_type:"portfolio"}),recordAsanaEntity:async()=>({id:"portfolio-context"})});assert.equal(membership.ok,true);assert.equal(membershipCalls,1);
  let portfolioProposal:any=null;const portfolioHandler=await handleAsanaWrite("u","Add Launch to my Roadmap Asana portfolio",{getTimezone:async()=>"UTC",extract:async()=>({provider:"asana",mode:"add_project",entity:"portfolio",targetPhrase:"Roadmap",projectName:"Launch"}),listResources:async(_u,kind)=>kind==="workspaces"?[{gid:"1",name:"Acme"}]:kind==="portfolios"?[{gid:"20",name:"Roadmap",resource_type:"portfolio"}]:[{gid:"30",name:"Launch",resource_type:"project"}],propose:async(_u,input)=>{portfolioProposal=input;return{id:"portfolio-proposal"} as any;}});assert.equal(portfolioProposal.actionId,"asana.portfolio.membership");assert.deepEqual(portfolioProposal.input,{portfolioId:"20",itemId:"30",operation:"addItem"});assert.match(portfolioHandler.reply??"",/Reply Yes/);
  for(const actionId of ["asana.section.write","asana.section.delete","asana.goal.write","asana.goal.delete","asana.time_entry.write","asana.time_entry.delete","asana.portfolio.delete"]){let forbiddenWrites=0;const blocked=await executeAction("u",actionId,{input:{operation:"create",resourceId:"1",data:{name:"X"}},userConfirmed:true},{buildContext:async()=>({connectedProviders:["asana"],grantedScopesByProvider:{asana:["goals:read","portfolios:write","time_tracking_entries:read"]},capabilitiesByProvider:{asana:["goals.read","portfolios.write","time_tracking.read"]},userConfirmed:true}),record:async()=>"b",createAsanaResource:async()=>{forbiddenWrites++;throw new Error("must not call")},deleteAsanaResource:async()=>{forbiddenWrites++;throw new Error("must not call")}});assert.equal(blocked.ok,false,actionId);assert.equal(forbiddenWrites,0,actionId);assert.match(blocked.userMessage,/do not authorise/i);}
  console.log("asana hierarchy tests passed");
}
void main();
