import assert from "node:assert/strict";
import { executeAction } from "../src/actions/executor";
import { explicitEntityKinds, resolveFollowupOwner } from "../src/actions/entityContextArbiter";
import { handleAsanaWrite } from "../src/integrations/providers/asana/asanaActions";
import { AsanaError } from "../src/integrations/providers/asana/client";
import { loadAsanaEntity, loadAsanaSelection, recordAsanaEntity, recordAsanaSelection, resolveAsanaReference } from "../src/integrations/providers/asana/asanaContext";
import { parseAsanaIntent, shouldConsiderAsana } from "../src/integrations/providers/asana/asanaIntentExtract";
import { handleAsanaRead } from "../src/integrations/providers/asana/asanaReads";
import { hasMarkdownSyntax } from "../src/integrations/providers/asana/plainText";
import { inboundHandlerOrder, routeInboundText } from "../src/routes/inboundRouting";
import type { ActionProposalView } from "../src/actions/proposals";

const task=(gid:string,name:string,completed=false)=>({gid,name,resource_type:"task",completed,due_on:"2026-07-16",assignee:{name:"Ada"},memberships:[{project:{name:"Launch"},section:{name:"In Progress"}}]});
function contextStore(){const rows:ActionProposalView[]=[];return{rows,store:{create:async(_u:string,input:any)=>{const now=new Date();const row={id:String(rows.length+1),provider:input.provider??null,actionId:input.actionId,status:"proposed",riskLevel:input.riskLevel,confirmationRequired:input.confirmationRequired??true,previewText:input.previewText,input:input.input??null,expiresAt:new Date(now.getTime()+(input.ttlMs??600000)).toISOString(),confirmedAt:null,rejectedAt:null,executedAt:null,createdAt:new Date(now.getTime()+rows.length).toISOString()} as ActionProposalView;rows.unshift(row);return{id:row.id};},listRecent:async(_u:string,a:string)=>rows.filter(r=>r.actionId===a)}};}

async function main(){
  assert.equal(shouldConsiderAsana("Could you show my Asana priorities?"),true);assert.equal(shouldConsiderAsana("Book a meeting Friday"),false);
  assert.equal(parseAsanaIntent('{"provider":"asana","mode":"read","entity":"task","count":7}')?.count,7);assert.equal(parseAsanaIntent("junk"),null);
  assert.deepEqual(explicitEntityKinds("complete that Asana task"),["asana_task"]);
  const ctx=contextStore();await recordAsanaSelection("u",[task("1","First"),task("2","Second")] as any,ctx.store);assert.equal((await loadAsanaSelection("u",ctx.store)).length,2);assert.equal((await resolveAsanaReference("u","the second one",null,null,ctx.store)).item?.id,"2");await recordAsanaEntity("u",{id:"2",type:"task",title:"Second",completed:false,project:null,section:null,due:null,permalink:null},"selected",ctx.store);assert.equal((await loadAsanaEntity("u",ctx.store))?.id,"2");
  const owner=await resolveFollowupOwner("u","complete it",{listRecent:async(_u,a)=>ctx.rows.filter(r=>r.actionId===a)});assert.equal(owner.kind,"owner");if(owner.kind==="owner")assert.equal(owner.owner,"asana_task");
  let recorded=0;const read=await handleAsanaRead("u","show my Asana tasks",{getTimezone:async()=>"Europe/London",extract:async()=>({provider:"asana",mode:"read",entity:"task",count:2}),listResources:async(_u,kind)=>kind==="workspaces"?[{gid:"w1",name:"Work",resource_type:"workspace"}] as any:[],listTasks:async(_u,params)=>{assert.equal(params!.workspace,"w1");return[task("1","First"),task("2","Second")] as any},recordSelection:async()=>{recorded++;return{id:"s"};}});assert.equal(read.handled,true);assert.match(read.reply??"",/1\. First/);assert.equal(recorded,1);
  let projectCalls=0;const oneWorkspaceProjects=await handleAsanaRead("u","Show me my Asana projects",{getTimezone:async()=>"Europe/London",extract:async()=>({provider:"asana",mode:"read",entity:"project"}),listResources:async(_u,kind,params)=>{if(kind==="workspaces")return[{gid:"w1",name:"Acme",resource_type:"workspace"}] as any;projectCalls++;assert.equal(kind,"projects");assert.equal(params!.workspace,"w1");return[{gid:"p1",name:"Launch",resource_type:"project"}] as any},recordSelection:async()=>({id:"projects"}),recordEntity:async()=>({id:"project"})});assert.match(oneWorkspaceProjects.reply??"",/^Here’s your Asana project:\nLaunch$/);assert.doesNotMatch(oneWorkspaceProjects.reply??"",/item/i);assert.equal(projectCalls,1);
  const pluralProjects=await handleAsanaRead("u","Show me my Asana projects",{getTimezone:async()=>"Europe/London",extract:async()=>({provider:"asana",mode:"read",entity:"project"}),listResources:async(_u,kind)=>kind==="workspaces"?[{gid:"w1",name:"Acme"}] as any:[{gid:"p1",name:"Launch",resource_type:"project"},{gid:"p2",name:"Website",resource_type:"project"}] as any,recordSelection:async()=>({id:"projects-2"})});assert.match(pluralProjects.reply??"",/^Here are your 2 Asana projects:/);assert.doesNotMatch(pluralProjects.reply??"",/items/i);
  const workspaceRead=await handleAsanaRead("u","Show my Asana workspaces",{getTimezone:async()=>"UTC",extract:async()=>({provider:"asana",mode:"read",entity:"workspace"}),listResources:async(_u,kind)=>{assert.equal(kind,"workspaces");return[{gid:"w1",name:"Acme",resource_type:"workspace"}] as any},recordSelection:async()=>({id:"workspace"}),recordEntity:async()=>({id:"workspace-entity"})});assert.match(workspaceRead.reply??"",/Asana workspace:\nAcme/);
  const currentUser=await handleAsanaRead("u","Who am I in Asana?",{getTimezone:async()=>"UTC",extract:async()=>({provider:"asana",mode:"read",entity:"user",person:"me"}),getCurrentUser:async()=>({gid:"7",name:"Ayub",email:"private@example.test",resource_type:"user"}),recordSelection:async()=>({id:"user"}),recordEntity:async()=>({id:"user-entity"})});assert.match(currentUser.reply??"",/Ayub/);assert.doesNotMatch(currentUser.reply??"",/private@example/);
  const customFields=await handleAsanaRead("u","Show Asana custom fields",{getTimezone:async()=>"UTC",extract:async()=>({provider:"asana",mode:"read",entity:"custom_field"}),listResources:async(_u,kind,params)=>kind==="workspaces"?[{gid:"w1",name:"Acme"}] as any:(assert.equal(kind,"custom_fields"),assert.equal(params!.workspace,"w1"),[{gid:"70",name:"Priority",resource_type:"custom_field",resource_subtype:"enum"}] as any),recordSelection:async()=>({id:"fields"}),recordEntity:async()=>({id:"field"})});assert.match(customFields.reply??"",/custom field:\nPriority/);
  const projectTaskFixture=[
    {gid:"99",name:"   ",resource_type:"task",resource_subtype:"section",memberships:[{project:{name:"Hula test"}}]},
    {...task("101","Define test objectives and success criteria"),due_on:"2026-07-15",memberships:[{project:{name:"Hula test"},section:{name:"Planning"}}]},
    {gid:"102",name:"Identify participants and assign roles",resource_type:"task",completed:false,due_on:"2026-07-16",assignee:null,memberships:[{project:{name:"Hula test"},section:{name:"Planning"}}]},
    {...task("103","Prepare **fixtures**"),due_on:"2026-07-17",memberships:[{project:{name:"Hula test"},section:{name:"In Progress"}}]},
    {gid:"104",name:"Run device checks",resource_type:"task",completed:false,due_at:"2026-07-17T16:00:00.000Z",assignee:null,memberships:[{project:{name:"Hula test"},section:{name:"In Progress"}}]},
    {...task("105","Review receipts"),due_on:"2026-07-19",memberships:[{project:{name:"Hula test"},section:{name:"Review"}}]},
    {gid:"106",name:"Archive test data",resource_type:"task",completed:false,assignee:null,memberships:[{project:{name:"Hula test"},section:{name:"Review"}}]},
    {gid:"107",name:"Present results",resource_type:"task",completed:false,assignee:null,memberships:[{project:{name:"Hula test"},section:{name:"Review"}}]},
  ];
  for(const requested of [2,5,7]){const countStore=contextStore();let shownProjectTasks:any[]=[];const projectTasks=await handleAsanaRead("u",`Show me the first ${requested} tasks in my Hula test Asana project`,{now:new Date("2026-07-15T12:00:00.000Z"),getTimezone:async()=>"Europe/London",extract:async()=>({provider:"asana",mode:"read",entity:"task",projectName:"Hula test",count:requested}),listResources:async(_u,kind,params)=>{if(kind==="workspaces")return[{gid:"1",name:"Acme"}] as any;assert.equal(kind,"projects");assert.equal(params!.workspace,"1");return[{gid:"10",name:"Hula test",resource_type:"project"}] as any},listTasks:async(_u,params)=>{assert.equal(params!.project,"10");assert.equal(params!.count,requested);assert.equal(params!.assignee,undefined);assert.equal(params!.workspace,undefined);return projectTaskFixture as any},recordSelection:async(_u,resources)=>{shownProjectTasks=resources;return recordAsanaSelection("u",resources,countStore.store)}});assert.equal(shownProjectTasks.length,requested);assert.match(projectTasks.reply??"",new RegExp(`^Here are ${requested} tasks in Hula test:`));assert.match(projectTasks.reply??"",/1\. Define test objectives.*due Today/);assert.match(projectTasks.reply??"",/2\. Identify participants.*due Tomorrow/);assert.doesNotMatch(projectTasks.reply??"",/Asana items?|2026-07-|^1\.\s+—/im);assert.equal(hasMarkdownSyntax(projectTasks.reply??""),false);assert.equal((await resolveAsanaReference("u","the second one",2,null,countStore.store)).item?.id,"102");}
  const detailStore=contextStore();await recordAsanaSelection("detail",projectTaskFixture.slice(1,6) as any,detailStore.store);let detailSelections=0;const detailTask={...projectTaskFixture[2],notes:"## Test notes\n- Include **unassigned** work",followers:[{gid:"8",name:"Ada"}],custom_fields:[{gid:"9",name:"Priority",display_value:"High"}],dependencies:[{gid:"55",name:"Prepare access"}]};const details=await handleAsanaRead("detail","Tell me more about the second one",{arbitrated:true,now:new Date("2026-07-15T12:00:00.000Z"),getTimezone:async()=>"Europe/London",extract:async()=>({provider:"asana",mode:"read",entity:"task",targetPosition:2}),resolveReference:async()=>resolveAsanaReference("detail","the second one",2,null,detailStore.store),getResource:async(_u,kind,id)=>{assert.equal(kind,"tasks");assert.equal(id,"102");return detailTask as any},listChildren:async(_u,_parent,id,child)=>{assert.equal(id,"102");return child==="subtasks"?[{gid:"201",name:"Draft report",resource_type:"task",completed:false},{gid:"202",name:"Review report",resource_type:"task",completed:true}] as any:[{gid:"55",name:"Prepare access",resource_type:"task"}] as any},recordSelection:async()=>{detailSelections++;return{id:"never"}},recordEntity:async()=>({id:"detail-entity"})});assert.equal(detailSelections,0);assert.match(details.reply??"",/^Task: Identify participants/);assert.match(details.reply??"",/Status: Open/);assert.match(details.reply??"",/Assignee: Unassigned/);assert.match(details.reply??"",/Description: Test notes; Include unassigned work/);assert.match(details.reply??"",/Custom fields: Priority: High/);assert.match(details.reply??"",/Dependencies: Prepare access/);assert.match(details.reply??"",/Subtasks: Open — Draft report; Complete — Review report/);assert.doesNotMatch(details.reply??"",/Want me|Asana items?/i);assert.equal(hasMarkdownSyntax(details.reply??""),false);assert.equal((await resolveAsanaReference("detail","the third one",3,null,detailStore.store)).item?.id,"103");
  let ambiguousProjectCalls=0;const multipleWorkspaces=await handleAsanaRead("u","Show me my Asana projects",{getTimezone:async()=>"UTC",extract:async()=>({provider:"asana",mode:"read",entity:"project"}),listResources:async(_u,kind)=>{if(kind==="workspaces")return[{gid:"w1",name:"Acme"},{gid:"w2",name:"Personal"}] as any;ambiguousProjectCalls++;return[]}});assert.match(multipleWorkspaces.reply??"",/Which Asana workspace.*Acme.*Personal/);assert.equal(ambiguousProjectCalls,0);
  let namedProjectCalls=0;const namedWorkspace=await handleAsanaRead("u","Show projects in my Personal Asana workspace",{getTimezone:async()=>"UTC",extract:async()=>({provider:"asana",mode:"read",entity:"project",workspaceName:"Personal"}),listResources:async(_u,kind,params)=>{if(kind==="workspaces")return[{gid:"w1",name:"Acme"},{gid:"w2",name:"Personal"}] as any;namedProjectCalls++;assert.equal(params!.workspace,"w2");return[{gid:"p2",name:"Home",resource_type:"project"}] as any},recordSelection:async()=>({id:"named"}),recordEntity:async()=>({id:"named-entity"})});assert.match(namedWorkspace.reply??"",/Home/);assert.equal(namedProjectCalls,1);
  let missingProjectCalls=0;const missingWorkspace=await handleAsanaRead("u","Show projects in Missing on Asana",{getTimezone:async()=>"UTC",extract:async()=>({provider:"asana",mode:"read",entity:"project",workspaceName:"Missing"}),listResources:async(_u,kind)=>{if(kind==="workspaces")return[{gid:"w1",name:"Acme"}] as any;missingProjectCalls++;return[]}});assert.match(missingWorkspace.reply??"",/couldn’t find an Asana workspace called “Missing”/);assert.equal(missingProjectCalls,0);
  const invalidProjects=await handleAsanaRead("u","Show me my Asana projects",{getTimezone:async()=>"UTC",extract:async()=>({provider:"asana",mode:"read",entity:"project"}),listResources:async(_u,kind)=>{if(kind==="workspaces")return[{gid:"w1",name:"Acme"}] as any;throw new AsanaError("malformed_response",200)}});assert.match(invalidProjects.reply??"",/couldn’t reach Asana/);assert.doesNotMatch(invalidProjects.reply??"",/200|malformed_response/);
  let proposed:any=null;const deletion=await handleAsanaWrite("u","delete the first Asana task",{getTimezone:async()=>"Europe/London",extract:async()=>({provider:"asana",mode:"delete",entity:"task",targetPosition:1}),resolveReference:async()=>({item:{id:"1",type:"task",title:"First",completed:false,project:null,section:null,due:null,permalink:null},ambiguous:false}),getResource:async()=>task("1","First") as any,propose:async(_u,input)=>{proposed=input;return{id:"p"} as any;}});assert.equal(deletion.handled,true);assert.equal(proposed.actionId,"asana.task.delete");assert.match(deletion.reply??"",/permanent/i);
  const comment=await handleAsanaWrite("u","comment on that Asana task",{getTimezone:async()=>"UTC",extract:async()=>({provider:"asana",mode:"comment",entity:"task",notes:"Ready for review"}),resolveReference:async()=>({item:{id:"1",type:"task",title:"First",completed:false,project:null,section:null,due:null,permalink:null},ambiguous:false}),getResource:async()=>task("1","First") as any,propose:async(_u,input)=>{proposed=input;return{id:"p2"} as any;}});assert.equal(comment.handled,true);assert.equal(proposed.actionId,"asana.task.comment");
  let writes=0;const ambiguousAssignee=await handleAsanaWrite("u","assign that Asana task to Sam",{getTimezone:async()=>"UTC",extract:async()=>({provider:"asana",mode:"assign",entity:"task",person:"Sam"}),resolveReference:async()=>({item:{id:"1",type:"task",title:"First",completed:false,project:null,section:null,due:null,permalink:null},ambiguous:false}),getResource:async()=>task("1","First") as any,listResources:async(_u,kind)=>kind==="workspaces"?[{gid:"9",name:"Work"}] as any:[],resolvePerson:async()=>({kind:"ambiguous",names:["Sam A","Sam B"]}),execute:async()=>{writes++;throw new Error("must not write")}});assert.match(ambiguousAssignee.reply??"",/multiple people/i);assert.equal(writes,0);
  const assigned=await handleAsanaWrite("u","assign that Asana task to sam@example.com",{getTimezone:async()=>"UTC",extract:async()=>({provider:"asana",mode:"assign",entity:"task",person:"sam@example.com"}),resolveReference:async()=>({item:{id:"1",type:"task",title:"First",completed:false,project:null,section:null,due:null,permalink:null},ambiguous:false}),getResource:async()=>task("1","First") as any,listResources:async(_u,kind)=>kind==="workspaces"?[{gid:"9",name:"Work"}] as any:[],resolvePerson:async()=>({kind:"resolved",user:{gid:"44",name:"Sam",email:"sam@example.com"}}),propose:async(_u,input)=>{proposed=input;return{id:"p3"} as any;}});assert.equal(assigned.handled,true);assert.deepEqual(proposed.input.fields,{assignee:"44"});
  const follower=await handleAsanaWrite("u","add Sam as a follower to that Asana task",{getTimezone:async()=>"UTC",extract:async()=>({provider:"asana",mode:"add_follower",entity:"task",person:"Sam"}),resolveReference:async()=>({item:{id:"1",type:"task",title:"First",completed:false,project:null,section:null,due:null,permalink:null},ambiguous:false}),getResource:async()=>task("1","First") as any,listResources:async(_u,kind)=>kind==="workspaces"?[{gid:"9",name:"Work"}] as any:[],resolvePerson:async()=>({kind:"resolved",user:{gid:"44",name:"Sam"}}),propose:async(_u,input)=>{proposed=input;return{id:"follower"} as any;}});assert.equal(proposed.input.relationshipAction,"addFollowers");assert.deepEqual(proposed.input.relationshipInput,{followers:["44"]});assert.match(follower.reply??"",/Reply Yes/);
  for(const [mode,expectedAction,related] of [["add_dependency","addDependencies","Blocker"],["remove_dependency","removeDependencies","Blocker"]] as const){let relationship:any=null;await handleAsanaWrite("u",mode,{arbitrated:true,getTimezone:async()=>"UTC",extract:async()=>({provider:"asana",mode,entity:"dependency",relatedTaskPhrase:related}),resolveReference:async()=>({item:{id:"1",type:"task",title:"First",completed:false,project:null,section:null,due:null,permalink:null},ambiguous:false}),getResource:async()=>task("1","First") as any,listResources:async()=>[{gid:"9",name:"Work"}] as any,listTasks:async()=>[task("2","Blocker")] as any,searchWorkspace:async()=>[task("2","Blocker")] as any,execute:async(_u,_a,options)=>{relationship=options!.input;return{ok:true,status:"succeeded",actionId:"asana.task.relationship",provider:"asana",userMessage:"Changed",executionId:mode,receipt:{asanaResourceIds:["1"]}}}});assert.equal(relationship.relationshipAction,expectedAction);assert.deepEqual(relationship.relationshipInput,{dependencies:["2"]});}
  let tagRelationship:any=null;await handleAsanaWrite("u","add the Urgent tag to that Asana task",{arbitrated:true,getTimezone:async()=>"UTC",extract:async()=>({provider:"asana",mode:"add_tag",entity:"tag",tagName:"Urgent"}),resolveReference:async()=>({item:{id:"1",type:"task",title:"First",completed:false,project:null,section:null,due:null,permalink:null},ambiguous:false}),getResource:async()=>task("1","First") as any,listResources:async(_u,kind)=>kind==="workspaces"?[{gid:"9",name:"Work"}] as any:[{gid:"80",name:"Urgent",resource_type:"tag"}] as any,execute:async(_u,_a,options)=>{tagRelationship=options!.input;return{ok:true,status:"succeeded",actionId:"asana.task.relationship",provider:"asana",userMessage:"Changed",executionId:"tag",receipt:{asanaResourceIds:["1"]}}}});assert.equal(tagRelationship.relationshipAction,"addTag");assert.deepEqual(tagRelationship.relationshipInput,{tag:"80"});
  const customTask={...task("1","First"),custom_fields:[{gid:"70",name:"Priority",resource_subtype:"enum",enum_options:[{gid:"71",name:"High",enabled:true}]}]};const custom=await handleAsanaWrite("u","set Priority to High on that Asana task",{getTimezone:async()=>"UTC",extract:async()=>({provider:"asana",mode:"set_custom_field",entity:"task",customFieldName:"Priority",customFieldValue:"High"}),resolveReference:async()=>({item:{id:"1",type:"task",title:"First",completed:false,project:null,section:null,due:null,permalink:null},ambiguous:false}),getResource:async()=>customTask as any,execute:async(_u,_a,options)=>{assert.deepEqual((options!.input as any).fields.custom_fields,{"70":"71"});return{ok:true,status:"succeeded",actionId:"asana.task.update",provider:"asana",userMessage:"Updated",executionId:"e",receipt:{asanaResourceIds:["1"]}}}});assert.equal(custom.reply,"Updated");
  const attachment=await handleAsanaWrite("u","attach https://example.com/spec to that Asana task",{getTimezone:async()=>"UTC",extract:async()=>({provider:"asana",mode:"attach_url",entity:"attachment",attachmentUrl:"https://example.com/spec"}),resolveReference:async()=>({item:{id:"1",type:"task",title:"First",completed:false,project:null,section:null,due:null,permalink:null},ambiguous:false}),getResource:async()=>task("1","First") as any,propose:async(_u,input)=>{proposed=input;return{id:"p4"} as any;}});assert.equal(proposed.actionId,"asana.task.attachUrl");assert.equal(proposed.input.relationshipInput.url,"https://example.com/spec");assert.match(attachment.reply??"",/Reply Yes/i);
  const subtask=await handleAsanaWrite("u","create subtask Draft under First in Asana",{getTimezone:async()=>"UTC",extract:async()=>({provider:"asana",mode:"create",entity:"subtask",name:"Draft",targetPhrase:"First"}),listResources:async(_u,kind)=>kind==="workspaces"?[{gid:"9",name:"Work"}] as any:[],listTasks:async()=>[task("1","First")] as any,searchWorkspace:async()=>[task("1","First")] as any,getResource:async()=>task("1","First") as any,execute:async(_u,_a,options)=>{assert.equal((options!.input as any).parent,"1");return{ok:true,status:"succeeded",actionId:"asana.task.create",provider:"asana",userMessage:"Created",executionId:"e",receipt:{asanaResourceIds:["2"]}}}});assert.equal(subtask.reply,"Created");
  let relationshipProposal:any=null;const addProject=await handleAsanaWrite("u","add that Asana task to Launch",{arbitrated:true,getTimezone:async()=>"UTC",extract:async()=>({provider:"asana",mode:"add_project",entity:"task",projectName:"Launch"}),resolveReference:async()=>({item:{id:"1",type:"task",title:"First",completed:false,project:null,section:null,due:null,permalink:null},ambiguous:false}),getResource:async()=>task("1","First") as any,listResources:async(_u,kind)=>kind==="workspaces"?[{gid:"9",name:"Work"}] as any:[{gid:"10",name:"Launch",resource_type:"project"}] as any,propose:async(_u,input)=>{relationshipProposal=input;return{id:"relationship"} as any;}});assert.equal(relationshipProposal.actionId,"asana.task.relationship");assert.deepEqual(relationshipProposal.input.relationshipInput,{project:"10"});assert.match(addProject.reply??"",/Reply Yes/);
  let archiveProposal:any=null;const archive=await handleAsanaWrite("u","archive the Launch Asana project",{getTimezone:async()=>"UTC",extract:async()=>({provider:"asana",mode:"archive",entity:"project",targetPhrase:"Launch"}),listResources:async(_u,kind)=>kind==="workspaces"?[{gid:"9",name:"Work"}] as any:[{gid:"10",name:"Launch",resource_type:"project"}] as any,propose:async(_u,input)=>{archiveProposal=input;return{id:"archive"} as any;}});assert.deepEqual(archiveProposal.input.data,{archived:true});assert.match(archive.reply??"",/Reply Yes/);
  for(const [label,intent,expected] of [["remove start",{removeStart:true},{start_on:null,start_at:null}],["remove due",{removeDue:true},{due_on:null,due_at:null}],["set start",{startDate:"2026-07-17",startTime:"09:00"},{start_at:"2026-07-17T09:00:00.000Z"}]] as const){let captured:any=null;const result=await handleAsanaWrite("u",label,{arbitrated:true,getTimezone:async()=>"UTC",extract:async()=>({provider:"asana",mode:"update",entity:"task",...intent}),resolveReference:async()=>({item:{id:"1",type:"task",title:"First",completed:false,project:null,section:null,due:null,permalink:null},ambiguous:false}),getResource:async()=>task("1","First") as any,execute:async(_u,_a,options)=>{captured=(options!.input as any).fields;return{ok:true,status:"succeeded",actionId:"asana.task.update",provider:"asana",userMessage:"Updated",executionId:"dates",receipt:{asanaResourceIds:["1"]}}}});assert.equal(result.reply,"Updated");assert.deepEqual(captured,expected);}
  for(const [mode,completed] of [["complete",true],["reopen",false]] as const){let captured:any=null;await handleAsanaWrite("u",`${mode} it`,{arbitrated:true,getTimezone:async()=>"UTC",extract:async()=>({provider:"asana",mode,entity:"task"}),resolveReference:async()=>({item:{id:"1",type:"task",title:"First",completed:!completed,project:null,section:null,due:null,permalink:null},ambiguous:false}),getResource:async()=>task("1","First",!completed) as any,execute:async(_u,_a,options)=>{captured=(options!.input as any).fields;return{ok:true,status:"succeeded",actionId:"asana.task.update",provider:"asana",userMessage:"Updated",executionId:mode,receipt:{asanaResourceIds:["1"]}}}});assert.deepEqual(captured,{completed});}
  let updates=0,remembered=0;const execution=await executeAction("u","asana.task.update",{input:{taskIds:["1"],fields:{completed:true}},userConfirmed:true},{buildContext:async()=>({connectedProviders:["asana"],grantedScopesByProvider:{asana:["tasks:write"]},capabilitiesByProvider:{asana:["tasks.write"]},userConfirmed:true}),record:async()=>"e1",updateAsanaTask:async()=>{updates++;return{gid:"1",resourceType:"task",name:"First",permalinkUrl:null,completed:true}},getAsanaResource:async()=>task("1","First",true) as any,recordAsanaEntity:async()=>{remembered++;return{id:"c"};}});assert.equal(execution.ok,true);assert.equal(updates,1);assert.equal(remembered,1);assert.deepEqual(execution.receipt?.asanaResourceIds,["1"]);
  const mismatch=await executeAction("u","asana.task.update",{input:{taskIds:["1"],fields:{completed:true}},userConfirmed:true},{buildContext:async()=>({connectedProviders:["asana"],grantedScopesByProvider:{asana:["tasks:write"]},capabilitiesByProvider:{asana:["tasks.write"]},userConfirmed:true}),record:async()=>"e2",updateAsanaTask:async()=>({gid:"1",resourceType:"task",name:"First",permalinkUrl:null,completed:true}),getAsanaResource:async()=>task("1","First",false) as any,recordAsanaEntity:async()=>{throw new Error("must not remember")}});assert.equal(mismatch.ok,false);
  assert.ok(inboundHandlerOrder().indexOf("asanaWrite")<inboundHandlerOrder().indexOf("todoistWrite"));const routed=await routeInboundText("u","show Asana",{transportKeyword:async()=>({handled:false}),memory:async()=>({handled:false}),reminder:async()=>({handled:false}),confirmation:async()=>({handled:false}),entityFollowup:async()=>({handled:false}),asanaWrite:async()=>({handled:false}),asanaRead:async()=>({handled:true,reply:"asana"}),pendingReprompt:async()=>({handled:false})});assert.equal(routed?.source,"asanaRead");
  console.log("asana conversation tests passed");
}
void main();
